"""One frozen X-Wing vector, replayed here and in the companion app.

``tests/test_push.py`` proves this daemon opens what this daemon sealed,
and the app's ``SealedBoxTests`` proves the same of CryptoKit.  Two
self-consistent implementations agree with themselves while drifting
apart from each other: a ``cryptography`` or CryptoKit release that
reordered a public key's halves, changed the X-Wing seed expansion or
reframed the wire blob would break every production alert and leave both
suites green.  This module and
``Packages/CronstableKit/Tests/CronstableKitTests/XWingVectorTests.swift``
(cronstable-ios) close that gap by replaying one fixture that neither
side generates.

The fixture is the production direction end to end: the daemon seals, the
app opens.  It holds a 32-byte X-Wing seed, the 1216-byte public key both
libraries derive from it, an alert plaintext, and that plaintext sealed to
that key by :func:`cronstable.push.seal_to_device`.  Each side derives the
keypair from the seed, asserts the derived public key is the frozen one
byte for byte, and opens the frozen blob.  A library that moves under
either side fails there while the other holds, and a suite that only
replays its own output cannot show that.

The seed is the app's own stable private form.  CryptoKit's
``XWingMLKEM768X25519.PrivateKey`` exposes ``seedRepresentation`` and takes
it back through ``init(seedRepresentation:publicKey:)``, and ``DeviceKey``
stores exactly those 32 bytes in the keychain.  ``cryptography`` has no
X-Wing composite keygen, so :func:`_private_key` expands the seed the way
draft-connolly-cfrg-xwing-kem specifies; that expansion is itself part of
what the vector pins.

Provenance: generated by ``tests/gen_push_vectors.py`` against
cryptography 50.0.1 (CPython 3.13, macOS 27 arm64), and verified to open
under CryptoKit in Xcode 27.0 (27A5252f, Swift 6.4).  Regenerate with
``python tests/gen_push_vectors.py``, which prints both suites' constant
blocks.

The ``requires_xwing`` guard is the shared one in ``tests/_helpers.py``,
the same marker ``tests/test_push.py`` rides on: cryptography is a dev
dependency with wheels on every CI cell but win-arm64, and only the
tests that touch key material stand down without it.  Never make this
a module-level ``importorskip``; that once vaporized the whole push suite
on cells that had the wheel.
"""

import base64
import hashlib
import json

import pytest

import cronstable.push as push
from tests._helpers import requires_xwing

# ------------------------------------------------------------ the vector

#: The device's private key, in the form the app stores in its keychain:
#: CryptoKit's 32-byte ``seedRepresentation``.
SEED_B64 = "tMHnDV8qk4TG7hAnvU+DpRyd5gJ/O0ig1RJ+yaNkH44="

#: The 1216-byte pairing key both libraries derive from that seed:
#: ML-KEM-768's 1184-byte encapsulation key, then X25519's 32.
PUBLIC_KEY_B64 = (
    "v8aoCEIFZSK/t4cAxMQuZlSk2xpfTQSQnPJKqYSq0yHH2yKVndEzLyoYMLByR9I1"
    "ijW5DxmR7ganNiC8oYrKJQFciCAH1TOWX4idf7ZObsiYcFyTnMGlGgOZyZBYkyUl"
    "7UwFNok7koh9usAzd1rNhUc3G0awdLkBYMCJHvEK6daRgzygI+wPWPWR6FKON5Zo"
    "kpUR2CC7wgC2hNCC79Q65Od6TTib5oGj7DMMn+OlBwAKdHDPRDAxw3SrsQabHztj"
    "cGaCWtyAnmdtSfw/RWZecoUElFmwWqRQ5dQip5WP+3EScfMhvVE5xskXwlloIASQ"
    "lVqzThyX3wgL5MupBijCwieqR7Gw3luAESSA3kiNYKYppMaSxugrVBy0PERRreTB"
    "O4hg38xjLMcpeQSYPHK9wEQikYCj2IGuaRfC3RpAZjzP0YsjTsGiGVkjwltbwHw9"
    "XKdU5ltK0UUOeytmFUdwY5MI0rLKHbS47zs+fHFZyfK7rri3lXZ0EAzH0hBaeNcu"
    "F5yILQZTu7xx82V63QloGwpR+RK5i2NEfksbJPVSRHVKIfhDcAOtTyQHN+gE+NqB"
    "xfMT/7KbIsc8aKfGV/F49WiTe9cIi+pgkxpLA/u+gJrGNZOl5OoaauMK/YVGIHPL"
    "CSguD+wnTiWkULl5Z3ZzSDSKqztO1BmDmHt+jnqDesGFBUVIDUxER/VqV1MVNqU7"
    "Mkg3Mjc7YokMmjikLlliTVHFhPyHQ9E/m6CNGXEkWdHGItAKKjlcxanIx3MmE1Eu"
    "ZMc6XHlEkMJ8eyk0JetQFDqn6OwWEmOK8/VKcHMe8Jaccls2nrs2DQsnORI5DyrG"
    "sZUIbXtWZcq+GKhU7wMB6QYNpyKQD6MDfshMPBWhMvM81nfICJgAqax372AagOpD"
    "/gGIWekTUPZ0ZNdHusDERRMj4tMnIcEwKhEuMUNpqkWqM3LG8Jw5rrMQDXpZ/qV/"
    "6jwi3GOCd+d7gXO2emJVV5CrDDqTVzxa0lvMxouoQfo4+psRiRFYDVcrLblpJyiG"
    "0RpRY7RAjAx04mSTc0Qtn+M8iiyz+iQ0mOcl2ncaqEZjdamRT5CQ0mpCB2IWNVJt"
    "I7q+vkdebwWmgpNE1MVfc9N8zvVnW4SYTIk0VrqGm6y08NtDxbADz2wHxRc8rOuE"
    "QeO/+SVuDoGu4eRLVdAjQpCIP5GtzeUuS3iE5KpG9jlRNoMbTGyWFTsmU4A6ehcT"
    "7jybYXDPq1aqNwQiUYnD3nyrdRNZDAe3n6cV9MKqo8o0K6sFdSNX/0Ktz7wMXSrL"
    "5HM2VuNfzGIhNOxM0XJl/hBg75eENThtYVFokFiEYmGBxjlJcQUlBXli7/djZ6WF"
    "4fh3qPiEZANIwHcPGTGcNANOl8LO42MtLAUsEpmzjEVPRkm8QWxZJrq210QDi/WZ"
    "IzquXOvFxgwYHXcuIxcwrlsvd1xddoaezHqR/VMZ0qiq9uORB0UywiEyRbschNw7"
    "Lhddg4duFbGKkNGk4EaF06x4x8WWBHBP7LUKoaQXAaFNfRBEl+hsuNEE15C3LrK+"
    "23doKN0l/0R0qbgVHftj/OQOSTZa1nj3JLavCN5BtxlSl2YvxSdlnG+mjI1rBOn/"
    "BKXoKIkq2L1g6U0fgyrjLA=="
)

#: One alert sealed to that key by :func:`cronstable.push.seal_to_device`:
#: the 1120-byte HPKE ``enc`` followed by the AEAD ciphertext.
CIPHERTEXT_B64 = (
    "tD3TfUbKi4vBVkJoiXOicjSno2eKI+YkhwYjohx1lZ7+lm71JC1P3sYTcAVmCzta"
    "4wqWyuCWYZvbpcDvFle777g8ZM1UTGQu9niWLujKLKCweBVN7JIBttsfCI1xIbiL"
    "ohgX5YstMkac2Twg2c40CXT0qpQo1p77rHUON88/Adl8MHrEL79MrTQVOQvwrR0R"
    "jWw/S9CqQl9eys0y9MPXrj9Yh3AZmYPPqBtuZQWQtV8+jcbrz+9z0XkQMXgsfi46"
    "r0SdtroQ3zMEk5AQN83pMa7zeCYBziNLi1M9xxTygDMb1urrXzLUDpddHxAReIuO"
    "c/yo6t5ZbqhgIk6ijMuhzMYFhYYE2Q9zjHsH3janQutZFrmfGL7z1BDo3r97Flae"
    "EZZcjrF1uv9OKHE/uGk1eA0TI4uytoYtHSCh6tHJiiFZNcMUZ/cdIettaCaql2xD"
    "dRw2JOR0KYDO3nJm7sIcFEcphuAHGgp6m0SE71rgcQn9h+fVIGsCWAEnP/eEKdD8"
    "VlJELYBwI1PctJFrYf8HIFJXb2Eq4iw6JNZVVAOvfV5V8rFmGiljOjVqlEzNGG0g"
    "tisRibBkCdHo5nxJzYBSB5k2/rrIuYVo9mte2hL4DYiyJ/FdVIz0jfvPwF2a+x/T"
    "tD4cq7aAGutWmZ1AC7TGkpyV5ekTVbZcKWn7t1o0/249+dE6ud586K3C1j97JQTj"
    "UJxHC8ze6yWLu+c3pNPEPCAjdJ4/+w28K5e5DNoCjMWlZ8npr3hDTburbUQOOYsP"
    "Kp7Mai3HlN+rTbfgqDe+AY+m/GEfRcnxOxKFmqVI7fQFhgGXno08gjekQtyPTtDR"
    "2em84jKwjbzQm/BYaTfwq0iF1DbudOJvLFIY960ngXzROxQdvzc9tD/q5C9w6EhI"
    "P11V+KHuXtqOmEqVDM1o97B2nQhqmgtTuCCAKxzQBhN4qS9Y/oU+iS1uS2AukKIl"
    "a3hQw5UIFvnDbPomEpm1rCmt3dngCJQ05QQB4e2Oj2A2Tqtz196T9+Ypn1N5e19r"
    "pS3yF4c00kZB7OAUtMc0q1Ibw4YM7xSib2pcZ8wBRC1XNhzWYX6ene7hOzOMgc7+"
    "i8xtFLOTduhI3rPQOQQrmoZ6wU4qTJ9D9KSHuWPovNAPjko7bea2ih3tS4bQV3/I"
    "N8uee3JswacZKva0F+ZiYMzteBC7w4cBkHmK6xA7h7NtpvAhj2AVYbh814kncerv"
    "CrtoK0LoSfIdRtrr+y7D57PcKbzqKA2+n+V+QBP659Iua4Vz2DH5xO6d5rB6Pn7A"
    "rPSyd/cUZAUnle/8xs3a4VWF0zwO+nFIxZQiN15j+9WfHXaegrDJ5dvbaXYzEG6r"
    "HE3nHP/VJUm5GnXMyMdj9bY4bLBvzXfPSxf++BRNtzINTYrIC6ezlzv6fi51sokQ"
    "8yyAld0eef9+Ri/neltjUvqpiwxQeRBd3yMsbrOr2EdKmt3pZ2H8hqHmumrfi9eH"
    "TUJAFOurjQ7dOQRG5ZzrLlGnoPRM4fUeeAD8rm2QARLXYuM6wxk7L6Lp0zFlAWEB"
    "MStfSL12C8ZZhB7d5/tfxec2PN6X3uBB1tVbgNdnOOASUlOv5Usy90N5RzXQcf4A"
    "pEEC4J2LKGkRIHaHHalNV039uJhjru2NFab/Pva1E9ybCzQQ2F09oErw6p7IaZE0"
    "smr82XDzpXA8MQT7ikzc5MaJMmnM"
)

#: What that blob opens to.
PLAINTEXT_JSON = (
    '{"v":1,"kind":"failure","host":"daemon.local","name":"nightly-ba'
    'ckup","success":false,"exit_code":1,"ts":"2026-08-31T04:00:00+00'
    ':00"}'
)
PLAINTEXT = PLAINTEXT_JSON.encode("utf-8")

#: The HPKE binding, spelled out rather than read from :mod:`cronstable.push`
#: so the vector pins the wire contract instead of the module's agreement
#: with itself.  The app binds the same bytes (``PushSuite.xwingInfo``).
INFO = b"cronstable-push-xwing"

#: Where the wire blob splits, and what sealing costs.  Duplicated from
#: docs/relay-protocol.md for the same reason as ``INFO``.
ENC_BYTES = 1120
OVERHEAD_BYTES = 1136
PUBLIC_KEY_BYTES = 1216


def _expand_seed(seed: bytes) -> tuple[bytes, bytes]:
    """An X-Wing seed split into its two private halves.

    draft-connolly-cfrg-xwing-kem's ``expandDecapsulationKey``: 96 bytes
    of SHAKE256 over the seed, read as the ML-KEM-768 d||z seed (which
    ``MLKEM768PrivateKey.from_seed_bytes`` takes, and which
    ``private_bytes_raw`` returns) followed by the X25519 private key.
    CryptoKit does this inside ``init(seedRepresentation:publicKey:)``;
    nothing in cryptography exposes it, so both halves of the vector
    ride on the two libraries expanding a seed identically.
    """
    expanded = hashlib.shake_256(seed).digest(96)
    return expanded[0:64], expanded[64:96]


def _private_key(seed: bytes):
    """The hybrid private key for ``seed``, and its 1216-byte wire key."""
    from cryptography.hazmat.primitives import hpke
    from cryptography.hazmat.primitives.asymmetric import mlkem, x25519

    mlkem_seed, x25519_seed = _expand_seed(seed)
    mlkem_private = mlkem.MLKEM768PrivateKey.from_seed_bytes(mlkem_seed)
    x_private = x25519.X25519PrivateKey.from_private_bytes(x25519_seed)
    wire = (
        mlkem_private.public_key().public_bytes_raw()
        + x_private.public_key().public_bytes_raw()
    )
    return hpke.MLKEM768X25519PrivateKey(mlkem_private, x_private), wire


def _open(sealed: bytes, private) -> bytes:
    """Open one X-Wing blob the way the app does: single-shot HPKE
    decrypt over the whole ``enc||ct`` wire form."""
    from cryptography.hazmat.primitives.hpke import AEAD, KDF, KEM, Suite

    suite = Suite(KEM.MLKEM768_X25519, KDF.HKDF_SHA256, AEAD.AES_256_GCM)
    return suite.decrypt(sealed, private, info=INFO)


# ------------------------------------------------------------- the tests


def test_the_vector_matches_the_daemons_own_suite_table():
    # The fixture's widths are quoted as literals above so the vector
    # stands alone; this ties those literals back to the table the rest
    # of the daemon sizes and validates against, so a table edit cannot
    # leave the vector describing a wire nobody speaks.
    spec = push.SUITES[push.SUITE_XWING]
    assert spec.public_key_bytes == PUBLIC_KEY_BYTES
    assert spec.overhead == OVERHEAD_BYTES
    assert len(base64.b64decode(PUBLIC_KEY_B64)) == PUBLIC_KEY_BYTES
    assert len(base64.b64decode(CIPHERTEXT_B64)) == (
        len(PLAINTEXT) + OVERHEAD_BYTES
    )


@requires_xwing
def test_the_frozen_seed_derives_the_frozen_public_key():
    # The cross-implementation pin on key derivation. CryptoKit expands
    # the same 32 bytes inside init(seedRepresentation:publicKey:) and
    # the Swift suite asserts the same equality against the same
    # constant, so a seed expansion, an ML-KEM keygen or a half-order
    # that moves under either library fails on one side.
    _, wire = _private_key(base64.b64decode(SEED_B64))
    assert base64.b64encode(wire).decode("ascii") == PUBLIC_KEY_B64
    # Named explicitly: the halves are ordered ML-KEM first, and the
    # ordering is the kind of thing a library release flips.
    assert len(wire[:1184]) == 1184
    assert len(wire[1184:]) == 32


@requires_xwing
def test_sealing_to_the_frozen_key_frames_the_documented_widths():
    # Framing is the other half of the contract the app's split depends
    # on: the app slices the first 1120 bytes off as the encapsulated
    # key and hands the rest to the AEAD, so enc width and total
    # overhead are wire, not an implementation detail.
    from cryptography.hazmat.primitives.hpke import KEM

    assert KEM.MLKEM768_X25519.enc_length() == ENC_BYTES
    sealed = base64.b64decode(
        push.seal_to_device(PUBLIC_KEY_B64, PLAINTEXT, push.SUITE_XWING)
    )
    assert len(sealed) == len(PLAINTEXT) + OVERHEAD_BYTES
    # enc, then the ciphertext and its 16-byte GCM tag.
    assert len(sealed) - ENC_BYTES == len(PLAINTEXT) + 16


@requires_xwing
def test_the_frozen_blob_opens_to_the_frozen_plaintext():
    # The vector replayed: bytes sealed under the library version named
    # in the module docstring open with the key the frozen seed rebuilds.
    # The Swift suite opens these exact bytes through CryptoKit.
    private, _ = _private_key(base64.b64decode(SEED_B64))
    opened = _open(base64.b64decode(CIPHERTEXT_B64), private)
    assert opened == PLAINTEXT
    # Shaped like a real alert, so the vector exercises a payload the app
    # actually renders rather than a token string.
    assert json.loads(opened.decode("utf-8"))["name"] == "nightly-backup"


@requires_xwing
def test_the_frozen_blob_stays_shut_under_a_different_info_string():
    # The info bytes are half the binding both sides commit to; a
    # daemon that changed them would seal blobs the app cannot open, and
    # the failure would look like a key problem. Pin it here.
    from cryptography.exceptions import InvalidTag
    from cryptography.hazmat.primitives.hpke import AEAD, KDF, KEM, Suite

    private, _ = _private_key(base64.b64decode(SEED_B64))
    suite = Suite(KEM.MLKEM768_X25519, KDF.HKDF_SHA256, AEAD.AES_256_GCM)
    with pytest.raises(InvalidTag):
        suite.decrypt(
            base64.b64decode(CIPHERTEXT_B64),
            private,
            info=b"cronstable-push-xwing ",
        )


@requires_xwing
def test_the_frozen_blob_stays_shut_under_a_different_seed():
    # One flipped seed bit is a different key pair, which is the property
    # the whole pairing model rests on.
    from cryptography.exceptions import InvalidTag

    seed = bytearray(base64.b64decode(SEED_B64))
    seed[0] ^= 0x01
    other, other_wire = _private_key(bytes(seed))
    assert base64.b64encode(other_wire).decode("ascii") != PUBLIC_KEY_B64
    with pytest.raises(InvalidTag):
        _open(base64.b64decode(CIPHERTEXT_B64), other)
