"""Test lease backends against real etcd and Kubernetes API servers.

These tests require configured servers. They run election scenarios and the
HTTP conformance checks in ``tests/_fake_conformance.py`` to verify that the
fake servers used by the transport tests match real server behavior.

Configure servers with these environment variables:

``CRONSTABLE_LIVE_ETCD``
    Comma-separated plaintext endpoints for an etcd server with
    authentication disabled, such as ``http://127.0.0.1:2379``.
``CRONSTABLE_LIVE_ETCD_AUTH``
    Comma-separated HTTPS endpoints for an etcd server with authentication
    enabled. Set ``CRONSTABLE_LIVE_ETCD_AUTH_PASSWORD`` and
    ``CRONSTABLE_LIVE_ETCD_AUTH_CA`` to the password and the CA certificate
    file used to verify the server. ``CRONSTABLE_LIVE_ETCD_AUTH_USER``
    defaults to ``root``. For client certificate authentication, also set
    ``CRONSTABLE_LIVE_ETCD_AUTH_CERT`` and ``CRONSTABLE_LIVE_ETCD_AUTH_KEY``.
``CRONSTABLE_LIVE_K8S=1``
    Use the first path in ``KUBECONFIG``, or ``~/.kube/config`` if unset.
    ``CRONSTABLE_LIVE_K8S_NAMESPACE`` selects the namespace and defaults to
    ``default``. The HTTP transport needs a kubeconfig with a static token
    or client certificate, such as one generated by kind. The library
    transport also runs if the ``kubernetes`` package is importable.
``CRONSTABLE_LIVE_REQUIRED=1``
    Fail any test that would otherwise skip. This prevents a successful CI
    result when a required server or cluster is unavailable.

Each test uses unique election key prefixes or Lease names and removes
what it creates. Waits poll until a deadline; expiration tests wait for
real leases to expire.
"""

import asyncio
import contextlib
import importlib.util
import os
import uuid

import aiohttp
import pytest

from cronstable.backends.etcd import EtcdBackend, _b64
from cronstable.backends.kubernetes import (
    KubernetesBackend,
    _K8sHttpTransport,
    _K8sLibraryTransport,
)
from cronstable.config import parse_config_string
from cronstable.leadership import REBOOT_RAN_KEY
from tests._fake_conformance import check_etcd_gateway, check_lease_api
from tests._fake_http import DEAD_ENDPOINT

_REQUIRED = os.environ.get("CRONSTABLE_LIVE_REQUIRED") == "1"
_RUN = uuid.uuid4().hex[:10]

# How long a poll waits for a real lease to expire and change hands. The
# leases below last 3-4 seconds; the rest is headroom for a loaded runner.
_FAILOVER_DEADLINE = 45.0


def _need(present, reason):
    """Skip if ``present`` is false, or fail if live tests are required."""
    if present:
        return
    if _REQUIRED:
        pytest.fail(reason + " (and CRONSTABLE_LIVE_REQUIRED=1)")
    pytest.skip(reason)


async def _poll(done, deadline=_FAILOVER_DEADLINE, interval=0.1):
    """Wait for ``done()`` or raise AssertionError after the deadline."""
    loop = asyncio.get_running_loop()
    give_up = loop.time() + deadline
    while not done():
        assert loop.time() < give_up, "condition not met within deadline"
        await asyncio.sleep(interval)


# --- etcd -----------------------------------------------------------------


def _etcd_endpoints(auth=False):
    var = "CRONSTABLE_LIVE_ETCD_AUTH" if auth else "CRONSTABLE_LIVE_ETCD"
    raw = os.environ.get(var, "")
    _need(bool(raw.strip()), var + " is not set: no live etcd to test against")
    return [e.strip() for e in raw.split(",") if e.strip()]


def _etcd_auth_extra():
    password = os.environ.get("CRONSTABLE_LIVE_ETCD_AUTH_PASSWORD")
    ca = os.environ.get("CRONSTABLE_LIVE_ETCD_AUTH_CA")
    _need(
        bool(password and ca),
        "CRONSTABLE_LIVE_ETCD_AUTH needs CRONSTABLE_LIVE_ETCD_AUTH_PASSWORD "
        "and CRONSTABLE_LIVE_ETCD_AUTH_CA",
    )
    extra = "    tls:\n      ca: '{}'\n".format(ca)
    cert = os.environ.get("CRONSTABLE_LIVE_ETCD_AUTH_CERT")
    key = os.environ.get("CRONSTABLE_LIVE_ETCD_AUTH_KEY")
    if cert and key:
        extra += "      cert: '{}'\n      key: '{}'\n".format(cert, key)
    user = os.environ.get("CRONSTABLE_LIVE_ETCD_AUTH_USER", "root")
    return extra + (
        "    username: '{}'\n    password:\n      value: '{}'\n".format(
            user, password
        )
    )


def _etcd_backend(endpoints, election, *, node="node-a", ttl=15, extra=""):
    yaml = (
        "cluster:\n"
        "  backend: etcd\n"
        "  nodeName: " + node + "\n"
        "  connectTimeout: 5\n"
        "  etcd:\n"
        "    endpoints:\n"
        + "".join("      - " + e + "\n" for e in endpoints)
        + "    electionName: "
        + election
        + "\n    ttl: "
        + str(ttl)
        + "\n"
        + extra
    )
    cfg = parse_config_string(yaml, "").cluster_config
    return EtcdBackend(cfg, lambda: "v1:live")


@contextlib.asynccontextmanager
async def _etcd_nodes(test, *, count=2, ttl=15, auth=False, dead_first=False):
    """``count`` backends on one run-unique election; cleans the keys up."""
    endpoints = _etcd_endpoints(auth)
    extra = _etcd_auth_extra() if auth else ""
    if dead_first:
        endpoints = [DEAD_ENDPOINT, *endpoints]
    election = "cronstable-live/{}/{}/leader".format(_RUN, test)
    nodes = [
        _etcd_backend(
            endpoints,
            election,
            node="node-" + "abcdef"[i],
            ttl=ttl,
            extra=extra,
        )
        for i in range(count)
    ]
    try:
        yield nodes
    finally:
        for node in nodes:
            await node.stop()
        janitor = _etcd_backend(endpoints, election, extra=extra)
        # a cleanup that cannot reach etcd must not mask the test's own error
        with contextlib.suppress(aiohttp.ClientError, asyncio.TimeoutError):
            await janitor.start()
            try:
                key = _b64(janitor.reboot_ran_key)
                await janitor._post("/v3/kv/deleterange", {"key": key})
            finally:
                # revokes the janitor's lease, deleting its election key
                await janitor.stop()


async def _etcd_holder(node):
    resp = await node._post("/v3/kv/range", {"key": _b64(node.election_name)})
    return (resp.get("kvs") or [None])[0]


async def test_live_etcd_gateway_matches_the_fake():
    endpoints = _etcd_endpoints()
    async with aiohttp.ClientSession() as http:

        async def call(path, body):
            async with http.post(endpoints[0] + path, json=body) as resp:
                return resp.status, await resp.json()

        await check_etcd_gateway(call, "cronstable-live/" + _RUN)


async def test_live_etcd_acquire_renew_release():
    async with _etcd_nodes("acquire", count=1) as [a]:
        await a.start()
        assert a.is_leader() and a.is_quorate()
        kv = await _etcd_holder(a)
        assert kv["lease"] == a.lease_detail()["leaseId"]
        for _ in range(3):
            await a._renew_once()
            assert a.is_leader()
        # renewing is a keepalive plus a read: the key is never rewritten
        assert (await _etcd_holder(a))["mod_revision"] == kv["mod_revision"]
        await a.stop()
        assert not a.is_leader()
        # revoking the lease deleted the key at once
        async with _etcd_nodes("acquire", count=1) as [probe]:
            await probe.start()
            assert probe.is_leader()


async def test_live_etcd_two_nodes_elect_one_leader_and_hand_over():
    async with _etcd_nodes("contention") as [a, b]:
        await a.start()
        await b.start()
        assert a.is_leader() and not b.is_leader()
        assert a.leader_name() == b.leader_name() == "node-a"
        first_term = int((await _etcd_holder(b))["create_revision"])
        for _ in range(3):
            await b._renew_once()
            await a._renew_once()
            assert [a.is_leader(), b.is_leader()] == [True, False]
        await a.stop()
        await b._renew_once()
        assert b.is_leader() and b.leader_name() == "node-b"
        # the new term's key is created at a strictly later revision
        assert int((await _etcd_holder(b))["create_revision"]) > first_term


async def test_live_etcd_concurrent_campaigns_elect_exactly_one():
    async with _etcd_nodes("stampede", count=5) as nodes:
        await asyncio.gather(*(node.start() for node in nodes))
        assert sum(node.is_leader() for node in nodes) == 1
        assert len({node.leader_name() for node in nodes}) == 1


async def test_live_etcd_leadership_moves_when_the_lease_expires():
    async with _etcd_nodes("expiry", ttl=3) as [a, b]:
        await a.start()
        await b.start()
        assert a.is_leader() and not b.is_leader()
        # the holder dies without revoking: its renew loop simply stops
        a._task.cancel()
        with contextlib.suppress(asyncio.CancelledError):
            await a._task
        a._task = None
        dead_lease = a._lease_id
        # the follower's own renew loop takes the lease over
        await _poll(b.is_leader)
        assert (await _etcd_holder(b))["lease"] == b._lease_id
        # the old holder's fence closed on its own clock, with no round
        assert not a.is_leader()
        # and when it comes back its keepalive finds the lease gone
        await a._renew_once()
        assert not a.is_leader()
        assert a._lease_id != dead_lease
        assert a.leader_name() == "node-b"


async def test_live_etcd_reboot_ran_marks_union_and_survive_failover():
    async with _etcd_nodes("reboot-ran") as [a, b]:
        await a.start()
        await b.start()
        await asyncio.gather(
            a.mark_reboot_ran("from-a"), b.mark_reboot_ran("from-b")
        )
        await a.stop()
        await b._renew_once()
        assert b.is_leader()
        assert b.reboot_ran("from-a") and b.reboot_ran("from-b")
        assert b.reboot_ran("never") is False


async def test_live_etcd_fails_over_from_a_dead_endpoint():
    async with _etcd_nodes("failover", count=1, dead_first=True) as [a]:
        await a.start()
        assert a.is_leader()
        for _ in range(2):
            await a._renew_once()
            assert a.is_leader()


async def test_live_etcd_with_auth_recovers_from_a_stale_token():
    async with _etcd_nodes("auth", count=1, auth=True) as [a]:
        await a.start()
        assert a.is_leader()
        assert a._auth_token
        # what an expired token looks like to the server
        a._auth_token = "stale.invalid-token"
        await a._renew_once()
        assert a.is_leader()
        assert a._auth_token != "stale.invalid-token"


async def test_live_etcd_auth_status_codes_match_the_fake():
    # The backend reauthenticates on 401 only. The fake answers an invalid
    # token with 401 and a token-less request with 400; hold real etcd to
    # the same.
    async with _etcd_nodes("auth-codes", count=1, auth=True) as [a]:
        await a.start()
        url = a.endpoints[0].rstrip("/") + "/v3/kv/range"
        body = {"key": _b64(a.election_name)}
        for headers, expected in (
            ({"Authorization": "stale.invalid-token"}, 401),
            ({}, 400),
        ):
            async with a._session.post(
                url, json=body, ssl=a._ssl, headers=headers
            ) as resp:
                assert resp.status == expected, await resp.text()


async def test_live_etcd_wrong_password_fails_start():
    endpoints = _etcd_endpoints(auth=True)
    extra = _etcd_auth_extra().replace(
        os.environ["CRONSTABLE_LIVE_ETCD_AUTH_PASSWORD"], "definitely-wrong"
    )
    a = _etcd_backend(endpoints, "cronstable-live/unused", extra=extra)
    with pytest.raises(aiohttp.ClientError):
        await a.start()
    assert a._session is None


# --- kubernetes -----------------------------------------------------------

_TRANSPORTS = {"http": _K8sHttpTransport, "library": _K8sLibraryTransport}


def _kubeconfig_path():
    _need(
        os.environ.get("CRONSTABLE_LIVE_K8S") == "1",
        "CRONSTABLE_LIVE_K8S is not 1: no live apiserver to test against",
    )
    first = os.environ.get("KUBECONFIG", "").split(os.pathsep)[0]
    path = first or os.path.join(os.path.expanduser("~"), ".kube", "config")
    _need(os.path.exists(path), "no kubeconfig at " + path)
    return path


def _need_transport(kind):
    if kind == "library":
        _need(
            importlib.util.find_spec("kubernetes") is not None,
            "the kubernetes package is not installed: the library transport "
            "cannot run live",
        )


def _k8s_backend(
    lease, kind, *, node="node-a", duration=15, renew=10, retry=2
):
    namespace = os.environ.get("CRONSTABLE_LIVE_K8S_NAMESPACE", "default")
    yaml = (
        "cluster:\n"
        "  backend: kubernetes\n"
        "  nodeName: " + node + "\n"
        "  connectTimeout: 5\n"
        "  kubernetes:\n"
        "    leaseName: " + lease + "\n"
        "    leaseNamespace: " + namespace + "\n"
        "    clientLibrary: " + kind + "\n"
        "    kubeconfig: '" + _kubeconfig_path().replace("\\", "/") + "'\n"
        "    leaseDurationSeconds: " + str(duration) + "\n"
        "    renewDeadlineSeconds: " + str(renew) + "\n"
        "    retryPeriodSeconds: " + str(retry) + "\n"
    )
    cfg = parse_config_string(yaml, "").cluster_config
    return KubernetesBackend(cfg, lambda: "v1:live")


@contextlib.asynccontextmanager
async def _raw_apiserver(lease):
    """``call(method, path, body)`` with the HTTP transport's credentials."""
    transport = _K8sHttpTransport(_k8s_backend(lease, "http"))
    await transport.setup()

    async def call(method, path, body):
        async with transport._session.request(
            method,
            transport._base_url + path,
            json=body,
            ssl=transport._ssl,
            headers=transport._auth_headers(),
        ) as resp:
            return resp.status, await resp.json()

    try:
        yield transport, call
    finally:
        await transport.close()


@contextlib.asynccontextmanager
async def _k8s_nodes(test, kinds, **timing):
    """One backend per entry of ``kinds`` on a run-unique Lease."""
    for kind in kinds:
        _need_transport(kind)
    lease = "cronstable-live-{}-{}".format(_RUN, test)
    nodes = [
        _k8s_backend(lease, kind, node="node-" + "abcdef"[i], **timing)
        for i, kind in enumerate(kinds)
    ]
    try:
        yield nodes
    finally:
        for node in nodes:
            await node.stop()
        async with _raw_apiserver(lease) as (transport, call):
            path = transport._lease_url()[len(transport._base_url) :]
            await call("DELETE", path, None)


async def _k8s_stored(lease):
    async with _raw_apiserver(lease) as (transport, _call):
        return await transport.observe()


async def test_live_apiserver_lease_api_matches_the_fake():
    namespace = os.environ.get("CRONSTABLE_LIVE_K8S_NAMESPACE", "default")
    name = "cronstable-live-{}-conformance".format(_RUN)
    async with _raw_apiserver(name) as (_transport, call):
        await check_lease_api(call, namespace, name)


@pytest.mark.parametrize("kind", ["http", "library"])
async def test_live_k8s_acquire_renew_release(kind):
    async with _k8s_nodes("acquire-" + kind, [kind]) as [a]:
        await a.start()
        assert type(a._transport) is _TRANSPORTS[kind]
        assert a.is_leader() and a.is_quorate()
        stored = await _k8s_stored(a.lease_name)
        assert stored["spec"]["holderIdentity"] == a.identity
        version = stored["metadata"]["resourceVersion"]
        for _ in range(3):
            await a._renew_once()
            assert a.is_leader()
        assert (await _k8s_stored(a.lease_name))["metadata"][
            "resourceVersion"
        ] != version
        await a.mark_reboot_ran("oneshot")
        await a.stop()
        # handed back: no holder, and the @reboot-ran annotation kept
        released = await _k8s_stored(a.lease_name)
        assert not released["spec"].get("holderIdentity")
        assert REBOOT_RAN_KEY in released["metadata"]["annotations"]


@pytest.mark.parametrize(
    "kinds",
    [("http", "http"), ("library", "library"), ("library", "http")],
    ids=["http", "library", "mixed"],
)
async def test_live_k8s_two_nodes_elect_one_leader_and_hand_over(kinds):
    async with _k8s_nodes("contention-" + "-".join(kinds), kinds) as [a, b]:
        await a.start()
        await b.start()
        assert a.is_leader() and not b.is_leader()
        assert a.leader_name() == b.leader_name() == "node-a"
        for _ in range(3):
            await b._renew_once()
            await a._renew_once()
            assert [a.is_leader(), b.is_leader()] == [True, False]
        await a.mark_reboot_ran("oneshot")
        await a.stop()
        await b._renew_once()
        assert b.is_leader() and b.leader_name() == "node-b"
        assert b.reboot_ran("oneshot") is True
        stored = await _k8s_stored(b.lease_name)
        assert stored["spec"]["holderIdentity"] == b.identity
        assert stored["spec"]["leaseTransitions"] == 1


@pytest.mark.parametrize("kind", ["http", "library"])
async def test_live_k8s_concurrent_cold_start_elects_exactly_one(kind):
    async with _k8s_nodes("stampede-" + kind, [kind] * 4) as nodes:
        await asyncio.gather(*(node.start() for node in nodes))
        assert sum(node.is_leader() for node in nodes) == 1
        assert all(node.leader_name() is not None for node in nodes)


@pytest.mark.parametrize("kind", ["http", "library"])
async def test_live_k8s_leadership_moves_when_the_holder_stops_renewing(kind):
    timing = {"duration": 4, "renew": 2, "retry": 1}
    async with _k8s_nodes("expiry-" + kind, [kind] * 2, **timing) as [a, b]:
        await a.start()
        await b.start()
        assert a.is_leader() and not b.is_leader()
        # the holder dies without releasing: its renew loop simply stops
        a._task.cancel()
        with contextlib.suppress(asyncio.CancelledError):
            await a._task
        a._task = None
        # the follower's own renew loop takes the lease over
        await _poll(b.is_leader)
        assert not a.is_leader()
        await a._renew_once()
        assert not a.is_leader()
        assert a.leader_name() == "node-b"
