"""Generate build inputs from pyproject.toml and the Docker image definitions.

Run with Python 3.11+: python scripts/generate_build_files.py [--check].
Generated files stay checked in, so builds and Python 3.10 contributors do
not need a generation step. This script uses only the standard library.
"""

import argparse
import json
import re
from pathlib import Path

import tomllib

ROOT = Path(__file__).resolve().parents[1]
GENERATED = (
    "# Generated by scripts/generate_build_files.py; edit pyproject.toml.\n"
)
TOKENS = re.compile(r"@@([a-z_]+)@@")
IMAGE_DEFAULTS = dict.fromkeys(
    (
        "build_args",
        "builder_env",
        "sodium",
        "runtime_install",
        "rust_setup",
        "rust_cleanup",
        "extra_labels",
    ),
    "",
)
IMAGE_DEFAULTS.update(
    python="python3", libc="gnu", entrypoint='["cronstable"]'
)


def extra_floors(project):
    """Binary lanes choose their own platforms/caps; share the version floors.

    Preserve that existing release policy rather than applying pip-extra
    markers to source builds on platforms the wheel-only extra excludes.
    """
    floors = {}
    for extra in ("speedups", "push"):
        for line in project["optional-dependencies"][extra]:
            name = re.match(r"[\w.-]+", line)[0].lower()
            versions = re.findall(r">=\s*([^,;\s]+)", line.split(";", 1)[0])
            if len(versions) != 1:
                raise ValueError(f"Expected one version floor: {line}")
            requirement = name + ">=" + versions[0]
            if floors.setdefault(name, requirement) != requirement:
                raise ValueError(f"Conflicting version floors for {name}")
    return floors


def render_dockerfile(template, image, orjson_requirement):
    values = IMAGE_DEFAULTS | image
    values.setdefault("runtime", values["builder"])
    values["wheel_libc"] = "musl" if values["libc"] == "musl" else "glibc"
    values["orjson_requirement"] = orjson_requirement
    # Empty optional blocks must not leave blank continuation lines in RUNs.
    lines = []
    for line in template.splitlines():
        rendered = TOKENS.sub(
            lambda match: values[match[1]].rstrip("\n"), line
        )
        if rendered or not TOKENS.fullmatch(line):
            lines.append(rendered)
    return "\n".join(lines) + "\n"


def generated_files(root=ROOT):
    project = tomllib.loads((root / "pyproject.toml").read_text())["project"]
    files = {
        "requirements_dev.txt": GENERATED
        + "# Install with: pip install -r requirements_dev.txt\n"
        + "\n".join(project["optional-dependencies"]["dev"])
        + "\n"
    }
    floors = extra_floors(project)
    for name, requirement in floors.items():
        files[f"pyinstaller/requirements/{name}.txt"] = requirement + "\n"
    matrix = json.loads((root / ".github/docker-matrix.json").read_text())
    images = tomllib.loads((root / "docker/images.toml").read_text())
    if {row["distro"] for row in matrix} != images.keys():
        raise ValueError(
            "Docker image definitions must match the release matrix"
        )
    template = (root / "docker/templates/Dockerfile").read_text()
    for row in matrix:
        files[row["dockerfile"]] = render_dockerfile(
            template, images[row["distro"]], floors["orjson"]
        )
    return files


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail on stale files"
    )
    args = parser.parse_args(argv)
    stale = []
    for relative, content in generated_files(ROOT).items():
        path = ROOT / relative
        if path.exists() and path.read_bytes() == content.encode("utf-8"):
            continue
        if args.check:
            stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content.encode("utf-8"))
            print(f"wrote {relative}")
    if stale:
        print("Stale generated files: " + ", ".join(stale))
        print("Run: python scripts/generate_build_files.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
