"""In-house cron expression engine.

:class:`CronTab` answers :meth:`CronTab.next` (when does this fire
next?), :meth:`CronTab.test` (does this instant match?),
:meth:`CronTab.prev` and :meth:`CronTab.occurrences`, plus read-only
properties exposing the parsed field sets.  Behavior is pinned by golden
vectors in ``tests/data/cron_golden.json`` (regenerated by
``tests/gen_cron_golden.py``, replayed by ``tests/test_cronexpr.py``);
its ``"extension": true`` entries pin the L-/W/# extensions.

The dialect (the "Schedules and Timezones" wiki page is the user docs):

- 5 fields ``minute hour dayOfMonth month dayOfWeek`` (implicit second 0,
  any year); 6 adds a trailing ``year``; 7 adds a leading ``second``.
- Values, lists, ranges, steps (``*/5``, ``1-9/2``; ``5/15`` runs to the
  field's end), case-insensitive month/weekday names.
- Weekdays 0-7, BOTH 0 and 7 Sunday; a range ending in 0 wraps its end to
  7 (``sat-sun``, ``6-0``); star/step expansion runs 0-6.
- ``L`` alone in day-of-month: the month's last day.  ``L<n>`` or
  ``L<a>-<b>`` in day-of-week: the month's LAST such weekday (``L5`` =
  last Friday).  No other field takes an ``L``.
- Extensions (each a parse error in the legacy dialect, so no old
  schedule changed meaning): day-of-month ``L-<n>`` (n days before the
  final day, n 1-30), ``<n>W`` (weekday Mon-Fri nearest day n, flipped
  inward at month edges, no fire when the month lacks day n), ``LW``
  (last weekday); day-of-week ``<d>#<n>`` (n-th such weekday, n 1-5, no
  fire when absent).  All are ordinary list items under the AND rule.
- ``@yearly``/``@annually``/``@monthly``/``@weekly``/``@daily``/``@hourly``
  expand to five-field forms; ``@reboot`` never reaches this parser;
  ``@midnight`` becomes ``@daily`` in the classic-crontab loader.
- ``?`` alone in either day field reads as ``*`` (Quartz); anywhere else
  an error, and Quartz-smelling parse errors carry a dialect hint.
- ``H`` (Jenkins-style, any field but year): a value hashed from the
  ``hash_key`` (the job name), salted per field, stable across restarts
  and hosts, so fleets spread while each job keeps ONE predictable slot.
  Forms ``H``, ``H(a-b)``, ``H/n``, ``H(a-b)/n``; rangeless day-of-month
  forms hash over 1-28.  No ``hash_key`` rejects ``H``;
  :attr:`CronTab.resolved_source` shows the hashed values.
- Restricted day-of-month AND day-of-week must BOTH match (``0 0 13 * 5``
  = Friday the 13th); Vixie cron fires on either.
- ``year`` accepts 1970-2099; :meth:`CronTab.test` does not bound an
  unrestricted year, but :meth:`CronTab.next` stops at 2099 and returns
  ``None`` when no occurrence remains.

Time model: ``next`` is strictly future (a matching "now" yields the
following occurrence) and runs in ``now``'s civil clock; an aware match
resolves in its zone (``fold=0``) and the delay is true elapsed seconds
across offset changes: a spring-forward gap label fires once at its
shifted time, an ambiguous fall-back wall time on its first occurrence
only.  ``LOCAL_ZONE`` is the host's local clock as a tzinfo, so a
local-clock schedule takes that same aware path under the host's DST
rules.  ``test`` reads civil fields, ignoring microseconds.  ``prev``
mirrors into the past (floor 1970); ``occurrences`` iterates real
instants, never yielding one twice.
"""

import datetime
import hashlib
import itertools
import re
import time
from bisect import bisect_left, bisect_right
from collections.abc import Iterable, Iterator, Mapping
from typing import (
    Optional,
)

__all__ = ["LOCAL_ZONE", "CronTab", "LocalZone", "expand_field"]

_MACROS = {
    "@yearly": "0 0 1 1 *",
    "@annually": "0 0 1 1 *",
    "@monthly": "0 0 1 * *",
    "@weekly": "0 0 * * 0",
    "@daily": "0 0 * * *",
    "@hourly": "0 * * * *",
}

_MONTH_NAMES = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}

_DOW_NAMES = {
    "sun": 0,
    "mon": 1,
    "tue": 2,
    "wed": 3,
    "thu": 4,
    "fri": 5,
    "sat": 6,
}

#: next() never searches past this year: the year column's maximum, and the
#: horizon that makes a never-occurring schedule (Feb 30) come back as
#: ``None`` instead of looping forever.
_YEAR_HORIZON = 2099

#: prev() never searches before this year: the year column's minimum, the
#: backward mirror of ``_YEAR_HORIZON``.
_YEAR_FLOOR = 1970

#: The first instant past the horizon, which prev() clamps a far-future
#: ``now`` to (see there).
_HORIZON_EDGE = datetime.datetime(_YEAR_HORIZON + 1, 1, 1)

#: How far back :meth:`CronTab._gap_rewound_seed` probes for a spring-forward.
#: 26 hours is wider than every IANA offset jump, including the date-line hops
#: (Samoa 2011, +24h), and no real zone transitions twice inside one window.
_GAP_PROBE = datetime.timedelta(hours=26)

#: The one-second step :meth:`CronTab._next_civil` and
#: :meth:`CronTab._prev_civil` take off ``now``; hoisted, it is on the
#: once-per-call path of next(), prev() and every occurrences() yield.
_ONE_SECOND = datetime.timedelta(seconds=1)

#: The UTC singleton; the aware loops in next(), prev() and occurrences()
#: convert through it once per candidate.
_UTC = datetime.timezone.utc


#: Days per month, indexed 1-12 (February's non-leap length); index 0 unused.
_MDAYS = (0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)


def _month_end(year: int, month: int) -> int:
    """The last day of ``month``, i.e. ``calendar.monthrange(y, m)[1]``.

    Spelled out rather than delegated: this sits in the hottest civil walk
    and ``calendar.monthrange`` is an order of magnitude dearer than the
    arithmetic.  ``month`` is always 1-12 by construction (the parser
    bounds the month column and every walk keeps it in range), so no
    validation is owed.
    """
    if month == 2 and year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):
        return 29
    return _MDAYS[month]


def _is_quartz_w(item: str) -> bool:
    """A day-field item in the nearest-weekday shape (``15W``, ``LW``): valid
    in day-of-month, hint fodder anywhere else."""
    body = item[:-1]
    return item.endswith("w") and (body == "l" or body.isdecimal())


def _is_trailing_l(item: str) -> bool:
    """A day-of-week item in Quartz's trailing-L shape (``5L``), which this
    dialect spells ``L5``."""
    return item.endswith("l") and item[:-1].isdecimal()


#: (day-of-month, day-of-week) column indexes per field count, for the
#: wrong-field hints in :func:`_quartz_hint`
_DAY_INDEXES = {5: (2, 4), 6: (2, 4), 7: (3, 5)}

#: accepted spellings of a hashed item: ``h``, ``h/n``, ``h(a-b)``,
#: ``h(a-b)/n`` (lowercased).  Anything else opening with ``h`` is a
#: malformed hash item, not a value (no month/weekday name starts with h).
_HASH_ITEM = re.compile(r"h(?:\((\d+)-(\d+)\))?(?:/(\d+))?\Z")

#: an item that opens with ``h`` (at the start of a field or after a
#: comma) is the only position an H item can occupy, so ``thu`` and
#: ``@hourly`` never trip this; runs on the lowercased expression
_ITEM_H = re.compile(r"(?:^|[\s,])h")

#: a rangeless ``H`` form (bare ``H`` or ``H/n``) in day-of-month hashes
#: over this range, not 1-31: a hashed day of 29-31 would silently skip
#: short months.  An explicit ``H(1-31)`` still opts in to the full range.
_HASH_DOM_END = 28


def _quartz_hint(fields: tuple[str, ...]) -> Optional[str]:
    """Extra text for a parse error that smells like Quartz syntax.

    ``#`` and ``W`` are part of this dialect but each is valid in exactly
    one field, and Quartz still differs in ways users trip over: a
    seconds-FIRST 6-field layout (here the 6th field is a trailing year)
    and last-weekday spelled ``5L`` (here ``L5``).
    """
    if "?" in fields and len(fields) == 6:
        return (
            "this looks like a 6-field Quartz expression (seconds "
            "first); here the 6th field is a year, so append a "
            "trailing '*' to read it as second minute hour "
            "day-of-month month day-of-week year"
        )
    dom_index, dow_index = _DAY_INDEXES.get(len(fields), (None, None))
    for index, field in enumerate(fields):
        for item in field.split(","):
            if "#" in item and index != dow_index:
                return (
                    "'#' (Quartz-style nth weekday, 5#3 = third Friday) "
                    "is only valid in the day-of-week field"
                )
            if _is_quartz_w(item) and index != dom_index:
                return (
                    "'W' (Quartz-style nearest weekday, 15W / LW) is "
                    "only valid in the day-of-month field"
                )
            if index == dow_index and _is_trailing_l(item):
                return (
                    "a trailing 'L' on a weekday is Quartz's last-weekday "
                    "form; this dialect spells it L<n> (L5 = last Friday)"
                )
    if "?" in fields:
        return (
            "'?' is only accepted standing alone in the day-of-month "
            "and day-of-week fields, where it reads as '*'"
        )
    return None


# (label, lo, hi, step_end, names): ``hi`` bounds explicit values, while
# ``step_end`` is the implicit end of star/bare-start expansions.  They only
# differ for the weekday field, where an explicit 7 is legal (Sunday again)
# but ``*`` and ``5/2`` expand over 0-6.
_SECOND = ("second", 0, 59, 59, None)
_MINUTE = ("minute", 0, 59, 59, None)
_HOUR = ("hour", 0, 23, 23, None)
_DOM = ("day-of-month", 1, 31, 31, None)
_MONTH = ("month", 1, 12, 12, _MONTH_NAMES)
_DOW = ("day-of-week", 0, 7, 6, _DOW_NAMES)
_YEAR = ("year", 1970, _YEAR_HORIZON, _YEAR_HORIZON, None)

_FieldSpec = tuple[str, int, int, int, Optional[Mapping[str, int]]]

#: field layouts by column count, mirroring ``CronTab.__init__``'s slicing
_LAYOUTS: Mapping[int, tuple[_FieldSpec, ...]] = {
    5: (_MINUTE, _HOUR, _DOM, _MONTH, _DOW),
    6: (_MINUTE, _HOUR, _DOM, _MONTH, _DOW, _YEAR),
    7: (_SECOND, _MINUTE, _HOUR, _DOM, _MONTH, _DOW, _YEAR),
}


def _hash_value(hash_key: str, label: str) -> int:
    """The stable integer a hashed item draws its value from.

    sha256 rather than ``hash()``: the slot must be identical across
    processes, restarts and hosts (PYTHONHASHSEED randomizes ``hash()``).
    Salted with the field label so ``H H * * *`` picks an uncorrelated
    minute and hour.
    """
    digest = hashlib.sha256(
        "{}\n{}".format(label, hash_key).encode("utf-8")
    ).digest()
    return int.from_bytes(digest[:8], "big")


def _expand_hash_item(
    item: str, low: str, spec: _FieldSpec, hash_key: Optional[str]
) -> str:
    """One ``H`` item, expanded to the explicit values it hashes to.

    Returns a comma-joined numeric list the ordinary item parser then
    treats like any other values, so ``H`` needs no cases in the matching
    or search code.
    """
    label, lo, hi, step_end, _names = spec
    if label == "year":
        raise ValueError(
            "'H' is not supported in the year field (a hashed year would "
            "pin the schedule to one arbitrary year)"
        )
    match = _HASH_ITEM.match(low)
    if match is None:
        raise ValueError(
            "invalid {} field {!r}: an 'H' item takes the forms H, H/n, "
            "H(a-b) or H(a-b)/n (numeric range only)".format(label, item)
        )
    if hash_key is None:
        raise ValueError(
            "'H' in the {} field needs a hash key (the job name), which "
            "this context does not supply".format(label)
        )
    a_text, b_text, step_text = match.groups()
    if a_text is not None:
        start, end = int(a_text, 10), int(b_text, 10)
        for value in (start, end):
            if not lo <= value <= hi:
                raise ValueError(
                    "{} value {} out of range [{}, {}]".format(
                        label, value, lo, hi
                    )
                )
        if start > end:
            raise ValueError(
                "{} range start {} > end {}".format(label, start, end)
            )
    else:
        start, end = lo, step_end
        if spec is _DOM:
            end = _HASH_DOM_END  # rangeless H, bare or H/n: never land
            # on a day short months lack; H(1-31) opts back in
    span = end - start + 1
    value = _hash_value(hash_key, label)
    if step_text is None:
        return str(start + value % span)
    step = int(step_text, 10)
    if step <= 0:
        raise ValueError(
            "{} step must be positive, got {}".format(label, step)
        )
    if step > span:
        raise ValueError(
            "{} step {} exceeds the H range's span of {} (the hashed "
            "offset could fall past the range's end)".format(label, step, span)
        )
    values = range(start + value % step, end + 1, step)
    return ",".join(str(v) for v in values)


def _expand_hash_field(
    text: str, spec: _FieldSpec, hash_key: Optional[str]
) -> str:
    """Replace every ``H`` item of one field with its hashed values.

    Case and non-``H`` items pass through byte-identical, so an expression
    without ``H`` is untouched.
    """
    items = text.split(",")
    out: list[str] = []
    changed = False
    for item in items:
        low = item.lower()
        if low.startswith("h"):
            out.append(_expand_hash_item(item, low, spec, hash_key))
            changed = True
        else:
            out.append(item)
    return ",".join(out) if changed else text


def _resolve(token: str, spec: _FieldSpec, item: str) -> int:
    """One value token -> int, via the field's name table or base 10."""
    label, lo, hi, _end, names = spec
    if names is not None and token in names:
        value = names[token]
    else:
        try:
            value = int(token, 10)
        except ValueError:
            raise ValueError(
                "invalid {} field {!r}".format(label, item)
            ) from None
    if not lo <= value <= hi:
        raise ValueError(
            "{} value {} out of range [{}, {}]".format(label, value, lo, hi)
        )
    return value


def _parse_item(item: str, spec: _FieldSpec) -> Iterable[int]:
    """Expand one comma-separated item (``*``, ``a``, ``a-b``, with ``/n``).

    Validation (golden-pinned): a step must be positive, no larger than
    the field's ``hi``, and ``start + step`` must land back inside the
    field's range (so ``*/12`` in the month field is rejected); a reversed
    range is an error, except that a day-of-week range ending in 0 wraps
    to 7.  Returns a concrete ``range`` (or one-tuple) rather than
    yielding: every caller drains it straight into ``set.update`` in C.
    """
    label, lo, hi, step_end, _names = spec
    head, slash, step_text = item.partition("/")
    step = 1
    if slash:
        if "/" in step_text:
            raise ValueError(
                "invalid {} field {!r}: more than one '/'".format(label, item)
            )
        try:
            step = int(step_text, 10)
        except ValueError:
            raise ValueError(
                "invalid {} step {!r}".format(label, item)
            ) from None
        if step <= 0:
            raise ValueError(
                "{} step must be positive, got {}".format(label, step)
            )
        if step > hi:
            raise ValueError(
                "{} step {} too large (max {})".format(label, step, hi)
            )
    if head == "*":
        start, end = lo, step_end
    elif "-" in head:
        a, _, b = head.partition("-")
        start = _resolve(a, spec, item)
        end = _resolve(b, spec, item)
        if end == 0 and spec is _DOW:
            # A day-of-week range ending in 0 reads its end as Sunday-as-7,
            # UNCONDITIONALLY: 6-0/sat-sun is Sat+Sun, and the degenerate
            # 0-0/sun-sun becomes 0-7, every day (a preserved quirk).
            end = 7
        if start > end:
            raise ValueError(
                "{} range start {} > end {}".format(label, start, end)
            )
    else:
        start = _resolve(head, spec, item)
        if not slash:
            return (start,)
        end = step_end
        if start > end:
            raise ValueError(
                "{} range start {} > end {}".format(label, start, end)
            )
    if slash and not lo <= start + step <= hi:
        raise ValueError(
            "{} step {} from {} escapes [{}, {}]".format(
                label, step, start, lo, hi
            )
        )
    return range(start, end + 1, step)


def expand_field(
    spec: str,
    lo: int,
    hi: int,
    names: Mapping[str, int] | None = None,
) -> list[int] | None:
    """Tolerantly enumerate one plain cron field, or ``None`` for an
    unrestricted ``*``/``?``.

    The describers' entry point (croninfo, and through it the TUI; the
    web page's ``describeCron`` carries a ``parseField`` port of the same
    rules).  It deliberately accepts a SUPERSET of :func:`_parse_item`
    (wrap-around ranges like ``fri-mon``, steps unchecked beyond being
    positive integers) and raises plain :exc:`ValueError` on malformed
    input, which the callers catch to degrade to their "Custom schedule"
    prose; affirmative prose is separately gated on the engine's own
    verdict, so the superset never describes text the daemon would
    refuse to load.  ``hi == 6`` marks the day-of-week field and enables
    its two quirks below (a range end of 0 reads as Sunday-as-7, a 7
    folds to 0), matching :func:`_parse_dow`.
    """
    spec = spec.strip().lower()
    if spec in ("*", "?"):
        return None

    def resolve(token: str) -> int | None:
        token = token.strip().lower()
        if names and token in names:
            return names[token]
        return int(token) if token.isdigit() else None

    out: set[int] = set()
    for part in spec.split(","):
        body, step = part, 1
        if "/" in part:
            body, step_text = part.split("/", 1)
            if not step_text.isdigit() or int(step_text) < 1:
                raise ValueError("bad step: %s" % part)
            step = int(step_text)
        if body == "*":
            start, end = lo, hi
        elif "-" in body:
            a, b = body.split("-", 1)
            start_v, end_v = resolve(a), resolve(b)
            if start_v is None or end_v is None:
                raise ValueError("bad field: %s" % part)
            if hi == 6 and end_v == 0:
                # a day-of-week range ending in 0 reads its end as
                # Sunday-as-7, unconditionally, exactly like the engine
                # (sat-sun works; 0-0 is every day, a preserved quirk),
                # so the prose cannot claim "Sunday" for a daily schedule
                end_v = 7
            start, end = start_v, end_v
        else:
            v = resolve(body)
            if v is None:
                raise ValueError("bad field: %s" % part)
            start, end = v, (hi if "/" in part else v)
        # Iterate range lazily (never list(range(...))): a huge endpoint like
        # "1-2000000000" would otherwise allocate billions of ints before the
        # per-value check below rejects it, an OOM that also defeats the
        # degrade-to-prose guarantee. range is lazy and the loop raises on the
        # first out-of-range value, so an over-range spec costs O(1) while
        # every accepted schedule still yields identical values.
        values: Iterable[int]
        if start <= end:
            values = range(start, end + 1, step)
        else:  # wrap-around range, e.g. fri-mon
            values = itertools.chain(
                range(start, hi + 1, step), range(lo, end + 1, step)
            )
        for v in values:
            v = 0 if (hi == 6 and v == 7) else v
            if v < lo or v > hi:
                # out-of-range values (month 13, dow 8, minute 60) would
                # index past the callers' prose name tables; raise so
                # they degrade to prose instead.
                raise ValueError("out of range: %s" % part)
            out.add(v)
    return sorted(out)


_DomParse = tuple[frozenset[int], frozenset[int], frozenset[int], bool]
_DowParse = tuple[frozenset[int], frozenset[int], frozenset[tuple[int, int]]]

#: A time of day as the three numbers a datetime constructor wants.
_HMS = tuple[int, int, int]

#: The time-of-day floor (or ceiling) the time walks take.  They read
#: only hour/minute/second, so a datetime serves as well as a time, and
#: the civil walks pass their seed through as is.
_TimeOfDay = datetime.time | datetime.datetime

#: How many distinct field texts each interning cache below keeps.  Fleets
#: have few distinct FIELD texts, so the cap is only reached by pathological
#: churn, but it must exist: a config whose field text changes on every
#: reload would otherwise grow the caches without bound.  Past the cap,
#: parsing falls back to building fresh values.
_FIELD_CACHE_MAX = 4096

#: Parsed field values, interned per ``(field label, text)``.  Every value a
#: field parser returns is immutable and every consumer is read-only, so
#: sharing across CronTabs is safe.
#:
#: No lock: a reload parses on a worker thread, and the worst a racing
#: writer can do is store an equal value twice or overshoot the cap by the
#: number of threads in flight.
_PLAIN_CACHE: dict[tuple[str, str], frozenset[int]] = {}
_DOM_CACHE: dict[str, _DomParse] = {}
_DOW_CACHE: dict[str, _DowParse] = {}

#: The sorted tuples the time-of-day and month/year searches bisect, keyed on
#: the (interned, hash-caching) frozenset they were built from.
_SORTED_CACHE: dict[frozenset[int], tuple[int, ...]] = {}

#: Shared empties for the L / W / # families, which almost no expression
#: uses (CPython has no empty-frozenset singleton).
_NO_INTS: frozenset[int] = frozenset()
_NO_NTH: frozenset[tuple[int, int]] = frozenset()


def _sorted_tuple(values: frozenset[int]) -> tuple[int, ...]:
    """``tuple(sorted(values))``, shared across every tab with that set."""
    shared = _SORTED_CACHE.get(values)
    if shared is not None:
        return shared
    shared = tuple(sorted(values))
    if len(_SORTED_CACHE) < _FIELD_CACHE_MAX:
        _SORTED_CACHE[values] = shared
    return shared


def _parse_plain(text: str, spec: _FieldSpec) -> frozenset[int]:
    """A field with no ``L`` forms (second/minute/hour/month/year)."""
    key = (spec[0], text)
    cached = _PLAIN_CACHE.get(key)
    if cached is not None:
        return cached
    values: set[int] = set()
    for item in text.split(","):
        if item.startswith("l"):
            raise ValueError(
                "'L' is only valid in the day-of-month and day-of-week "
                "fields, not {}".format(spec[0])
            )
        values.update(_parse_item(item, spec))
    # the store sits after every raise, so a rejected field is re-rejected
    # with the same message rather than served from the cache
    result = frozenset(values)
    if len(_PLAIN_CACHE) < _FIELD_CACHE_MAX:
        _PLAIN_CACHE[key] = result
    return result


def _parse_dom(text: str) -> _DomParse:
    """Day-of-month: plain values plus the ``L`` and ``W`` families.

    Returns ``(values, last_offsets, nearest, last_weekday)``: explicit
    days, offsets back from the month's final day (0 for ``L``, 3 for
    ``L-3``), the ``<n>W`` target days, and whether ``LW`` was given.
    """
    cached = _DOM_CACHE.get(text)
    if cached is not None:
        return cached
    values: set[int] = set()
    last_offsets: set[int] = set()
    nearest: set[int] = set()
    last_weekday = False
    for item in text.split(","):
        if item == "l":
            last_offsets.add(0)
        elif item == "lw":
            last_weekday = True
        elif item.startswith("l-"):
            offset_text = item[2:]
            if not offset_text.isdigit():
                raise ValueError(
                    "an 'L-' day-of-month item takes a plain offset 1..30 "
                    "counted back from the month's final day "
                    "(got {!r})".format(item)
                )
            offset = int(offset_text, 10)
            if not 1 <= offset <= 30:
                raise ValueError(
                    "day-of-month 'L-' offset {} out of range [1, 30] "
                    "(L-1 is the day before the month's final day; for "
                    "the final day itself write L)".format(offset)
                )
            last_offsets.add(offset)
        elif item.startswith("l"):
            raise ValueError(
                "'L' in the day-of-month field takes the forms L (the "
                "month's final day), L-<n> (n days before it) or LW (its "
                "last weekday), got {!r}".format(item)
            )
        elif item.endswith("w"):
            day_text = item[:-1]
            if not day_text.isdigit():
                raise ValueError(
                    "a 'W' day-of-month item takes a plain day 1..31 and "
                    "fires on the weekday nearest that day "
                    "(got {!r})".format(item)
                )
            day = int(day_text, 10)
            if not 1 <= day <= 31:
                raise ValueError(
                    "day-of-month value {} out of range [1, 31]".format(day)
                )
            nearest.add(day)
        else:
            values.update(_parse_item(item, _DOM))
    result: _DomParse = (
        frozenset(values),
        frozenset(last_offsets) if last_offsets else _NO_INTS,
        frozenset(nearest) if nearest else _NO_INTS,
        last_weekday,
    )
    if len(_DOM_CACHE) < _FIELD_CACHE_MAX:
        _DOM_CACHE[text] = result
    return result


def _parse_dow(text: str) -> _DowParse:
    """Day-of-week: plain values, ``L``-prefixed items and ``#`` items.

    Returns ``(values, last, nth)``: plain weekdays, ``L<n>`` weekdays,
    and the (weekday, ordinal) pairs of ``<d>#<n>`` items.  All weekday
    sets are normalized so 7 (Sunday) is stored as 0; matching then never
    needs the 0/7 equivalence.
    """
    cached = _DOW_CACHE.get(text)
    if cached is not None:
        return cached
    values: set[int] = set()
    last: set[int] = set()
    nth: set[tuple[int, int]] = set()
    for item in text.split(","):
        if item == "l":
            raise ValueError(
                "a bare 'L' is only valid in the day-of-month field; in "
                "day-of-week write L<n> (e.g. L5 = last Friday)"
            )
        if item.startswith("l"):
            # L<n> or L<a>-<b>, strictly numeric (no names, steps or `*`),
            # each value 0..7.  Unlike a plain range, a reversed L-range is
            # NOT an error -- it is legal and matches nothing -- and an end
            # of 0 stays 0 (no Sunday-as-7 wrap).  Preserved quirks.
            a, dash, b = item[1:].partition("-")
            if not a.isdigit() or (dash and not b.isdigit()):
                raise ValueError(
                    "an L day-of-week item takes a day number or numeric "
                    "range 0..7, got {!r}".format(item)
                )
            lo = int(a, 10)
            hi = int(b, 10) if dash else lo
            for value in (lo, hi):
                if not 0 <= value <= 7:
                    raise ValueError(
                        "day-of-week value {} out of range [0, 7]".format(
                            value
                        )
                    )
            last.update(range(lo, hi + 1))
        elif "#" in item:
            # <d>#<n>: the month's n-th such weekday.  One weekday value
            # (numeric or named, no ranges, steps or `*`) and an ordinal
            # 1..5; a month without an n-th such weekday does not fire.
            day_text, _, ordinal_text = item.partition("#")
            if "#" in ordinal_text:
                raise ValueError(
                    "invalid day-of-week field {!r}: more than one '#'".format(
                        item
                    )
                )
            day = _resolve(day_text, _DOW, item)
            if not ordinal_text.isdigit():
                raise ValueError(
                    "a '#' day-of-week item is <weekday>#<n>, the month's "
                    "n-th such weekday (5#3 = third Friday), "
                    "got {!r}".format(item)
                )
            ordinal = int(ordinal_text, 10)
            if not 1 <= ordinal <= 5:
                raise ValueError(
                    "day-of-week '#' ordinal {} out of range [1, 5] (no "
                    "month holds more than five of one weekday)".format(
                        ordinal
                    )
                )
            nth.add((day % 7, ordinal))
        else:
            values.update(_parse_item(item, _DOW))
    result: _DowParse = (
        frozenset(v % 7 for v in values),
        frozenset(v % 7 for v in last) if last else _NO_INTS,
        frozenset(nth) if nth else _NO_NTH,
    )
    if len(_DOW_CACHE) < _FIELD_CACHE_MAX:
        _DOW_CACHE[text] = result
    return result


def _shift_to_weekday(
    year: int, month: int, target: int, month_end: int
) -> int:
    """The day a ``W`` item fires on for day ``target``: the nearest weekday.

    A Saturday resolves to the Friday before, a Sunday to the Monday
    after, flipped inward at the month's edges so the fire never leaves
    the month.  ``LW`` is this with ``target = month_end``.
    """
    weekday = datetime.date(year, month, target).weekday()  # Mon=0..Sun=6
    if weekday == 5:  # Saturday
        return target - 1 if target > 1 else target + 2
    if weekday == 6:  # Sunday
        return target + 1 if target < month_end else target - 2
    return target


def _default_now(default_utc: bool) -> datetime.datetime:
    """The reference instant when a caller omits one: the UTC or the
    local wall clock, naive either way.  The shared seed of
    :meth:`CronTab.next`, :meth:`CronTab.prev` and
    :meth:`CronTab.occurrences`, whose ``default_utc`` flags matter only
    on this path.
    """
    if default_utc:
        return datetime.datetime.now(_UTC).replace(tzinfo=None)
    return datetime.datetime.now()


def _host_civil(utc: datetime.datetime) -> datetime.datetime:
    """The C library's reading of the aware UTC instant ``utc``: aware,
    carrying that instant's fixed offset and zone name.  Raises outside
    the library's time_t range (the MS CRT: 1970 to 3001)."""
    return utc.astimezone()


def _host_instant(civil: datetime.datetime) -> datetime.datetime:
    """The aware UTC instant the C library resolves the naive label
    ``civil`` to; ``civil.fold`` picks the reading of a gap or a repeat.
    Raises as :func:`_host_civil` does (the resolution probes a day to
    either side)."""
    return civil.astimezone(_UTC)


#: 2001..2028 holds every calendar layout (weekday of 1 January, length
#: of February), so a proxy year keeps DST rules on the same dates.
_PROXY_YEARS = {
    (datetime.date(y, 1, 1).weekday(), _month_end(y, 2)): y
    for y in range(2001, 2029)
}


def _proxy(dt: datetime.datetime) -> datetime.datetime:
    """``dt`` moved to the proxy year that shares its calendar layout."""
    year = dt.year
    layout = (datetime.date(year, 1, 1).weekday(), _month_end(year, 2))
    return dt.replace(year=_PROXY_YEARS[layout])


def _local_civil(utc: datetime.datetime) -> datetime.datetime:
    """:func:`_host_civil`, total over datetime's range: outside the
    library's range the proxy year's offset applies."""
    try:
        return _host_civil(utc)
    except (OSError, OverflowError, ValueError):
        return utc.astimezone(_host_civil(_proxy(utc)).tzinfo)


def _local_instant(civil: datetime.datetime) -> datetime.datetime:
    """:func:`_host_instant`, total over datetime's range."""
    try:
        return _host_instant(civil)
    except (OSError, OverflowError, ValueError):
        proxy = _proxy(civil)
        offset = proxy - _host_instant(proxy).replace(tzinfo=None)
        return (civil - offset).replace(tzinfo=_UTC)


#: How far past a probed instant :meth:`LocalZone.fixed_frame` samples
#: the host offset when nothing bounds the request; one frame then serves
#: a month of scheduler passes.
_FRAME_SPAN = datetime.timedelta(days=35)

#: A frame is re-sampled after this many seconds, so a host whose zone
#: changes while the daemon runs follows the new rules within a minute.
_FRAME_TTL = 60.0

#: Frames sample hourly: a transition changes the offset for months, never
#: for under an hour, so no change hides between two samples.
_FRAME_STEP = datetime.timedelta(hours=1)

#: Frames kept per zone: the live scheduler asks around now while a
#: catch-up walk asks around an old watermark, and neither may evict the
#: other on every call.
_FRAMES_KEPT = 4


class _Frame:
    """The host offset verdict for instants in ``[lo, hi)``, both UTC.

    ``fixed`` is the :class:`datetime.timezone` the host keeps from
    ``lo - _GAP_PROBE`` through ``hi``, or None when a transition sits
    inside that reach.  ``open`` says ``hi`` is the sampling horizon
    rather than a transition, so the frame may be extended.
    """

    __slots__ = ("lo", "hi", "fixed", "open", "built")

    def __init__(
        self,
        lo: datetime.datetime,
        hi: datetime.datetime,
        fixed: Optional[datetime.timezone],
        open: bool,
    ) -> None:
        self.lo = lo
        self.hi = hi
        self.fixed = fixed
        self.open = open
        self.built = time.monotonic()


def _host_offset(utc: datetime.datetime) -> Optional[datetime.timedelta]:
    """The host offset at the aware instant ``utc``: one library reading."""
    return _local_civil(utc).utcoffset()


def _first_change(
    start: datetime.datetime,
    stop: datetime.datetime,
    offset: Optional[datetime.timedelta],
) -> Optional[datetime.datetime]:
    """The first hourly sample after ``start``, reaching ``stop``, whose
    host offset is not ``offset``; None when every sample agrees."""
    at = start
    while at < stop:
        at += _FRAME_STEP
        if _host_offset(at) != offset:
            return at
    return None


def _build_frame(
    at: datetime.datetime, until: Optional[datetime.datetime]
) -> _Frame:
    origin = at - _GAP_PROBE
    first = _local_civil(origin)
    offset = first.utcoffset()
    assert offset is not None
    name = first.tzname()
    fixed = (
        datetime.timezone(offset)
        if name is None
        else datetime.timezone(offset, name)
    )
    stop = at + _FRAME_SPAN
    if until is not None and until > stop:
        stop = until
    change = _first_change(origin, stop, offset)
    if change is None:
        return _Frame(at, stop, fixed, True)
    # the transition sits in (change - step, change]: every instant whose
    # look-back can hold it, from change - step to change + _GAP_PROBE,
    # walks aware; the instants before it keep the offset through the
    # last agreeing sample
    if at >= change - _FRAME_STEP:
        return _Frame(at, change + _GAP_PROBE, None, False)
    return _Frame(at, change - _FRAME_STEP, fixed, False)


def _extend_frame(frame: _Frame, until: datetime.datetime) -> None:
    """Sample an open frame's host offset on to ``until``."""
    assert frame.fixed is not None
    change = _first_change(frame.hi, until, frame.fixed.utcoffset(None))
    if change is None:
        frame.hi = until
    else:
        frame.hi = change - _FRAME_STEP
        frame.open = False


class LocalZone(datetime.tzinfo):
    """The host's local clock as a tzinfo.

    Every offset is the C library's live answer (:func:`_local_civil`,
    :func:`_local_instant`), so a local-clock schedule takes the same
    aware path as a zoned one and follows the host's own DST rules;
    ``fold`` reads as in PEP 495.  ``dst`` is unknown (None): the
    library reports the whole offset, never its DST share.
    :meth:`fixed_frame` hands a walk the fixed offset the host keeps
    across its reach, where the engine's fixed-offset path answers the
    same instants at a fraction of the cost.
    """

    def __init__(self) -> None:
        self._frames: list[_Frame] = []

    def fixed_frame(
        self,
        at: datetime.datetime,
        until: Optional[datetime.datetime] = None,
    ) -> tuple[Optional[datetime.timezone], datetime.datetime]:
        """The host clock as a fixed offset around the aware instant ``at``.

        Returns ``(fixed, good_to)``.  ``fixed`` is a
        :class:`datetime.timezone` equal to this zone from ``at`` less
        :data:`_GAP_PROBE` (the engine's look-back) through ``good_to``,
        so a walk from ``at`` whose instants stay at or before ``good_to``
        answers the same on it as on this zone; None when a transition
        sits inside that reach, ``good_to`` then being the instant from
        which to ask again.  ``until`` extends the sampled span so a
        window ending there is covered.  Frames are sampled hourly, kept
        per process and re-sampled after :data:`_FRAME_TTL`.
        """
        at = at.astimezone(_UTC)
        if until is not None:
            until = until.astimezone(_UTC)
        frames = self._frames
        now = time.monotonic()
        for frame in frames:
            if frame.lo <= at < frame.hi and now - frame.built < _FRAME_TTL:
                if until is not None and frame.open and frame.hi < until:
                    _extend_frame(frame, until)
                return frame.fixed, frame.hi
        try:
            frame = _build_frame(at, until)
        except OverflowError:  # within _GAP_PROBE of datetime's range
            return None, at
        kept = [f for f in frames if now - f.built < _FRAME_TTL]
        self._frames = [frame] + kept[: _FRAMES_KEPT - 1]
        return frame.fixed, frame.hi

    def utcoffset(
        self, dt: Optional[datetime.datetime]
    ) -> Optional[datetime.timedelta]:
        if dt is None:
            return None
        civil = dt.replace(tzinfo=None)
        return civil - _local_instant(civil).replace(tzinfo=None)

    def dst(
        self, dt: Optional[datetime.datetime]
    ) -> Optional[datetime.timedelta]:
        return None

    def tzname(self, dt: Optional[datetime.datetime]) -> Optional[str]:
        if dt is None:
            return "local"
        # the name in force at the instant the label resolves to
        return _local_civil(_local_instant(dt.replace(tzinfo=None))).tzname()

    def fromutc(self, dt: datetime.datetime) -> datetime.datetime:
        utc = dt.replace(tzinfo=_UTC)
        civil = _local_civil(utc).replace(tzinfo=None, fold=0)
        # the second leg of a repeated wall time is the instant its
        # fold=0 reading does not give back
        fold = 0 if _local_instant(civil) == utc else 1
        return civil.replace(tzinfo=self, fold=fold)

    def __repr__(self) -> str:
        return "LocalZone()"

    def __str__(self) -> str:
        return "local"


#: The one host-clock frame: every local-clock job and view shares it.
LOCAL_ZONE = LocalZone()


class CronTab:
    """One parsed cron expression; see the module docstring for the dialect.

    Equality is semantic (``*/5 * * * *`` == ``0-59/5 * * * *``): the
    scheduler's reload path uses ``==`` to keep an unchanged job's
    next-fire instant (see ``Cron._same_schedule``).  Instances are
    deliberately unhashable.  ``str()`` is the whitespace-normalized
    source, giving the dag scheduler's schedule signature a stable value
    across reloads.
    """

    __slots__ = (
        "_source",
        "_resolved",
        "_seconds",
        "_minutes",
        "_hours",
        "_dom",
        "_dom_last_offsets",
        "_dom_nearest",
        "_dom_last_weekday",
        "_months",
        "_dow",
        "_dow_last",
        "_dow_nth",
        "_years",
        "_hours_sorted",
        "_minutes_sorted",
        "_seconds_sorted",
        "_months_sorted",
        "_years_sorted",
        "_dom_sorted",
        "_first_hms",
        "_last_hms",
        "_dow_free",
        "_days_plain",
        "_resolved_differs",
    )

    def __init__(self, crontab: str, hash_key: Optional[str] = None) -> None:
        self._source = " ".join(crontab.split())
        self._resolved = self._source
        lowered = crontab.lower()
        fields = lowered.split()
        # Skip the (not cheap) H expansion when no item opens with 'h';
        # ``display is None`` means "nothing to resolve".  The expansion
        # only acts on an item-opening h, so the probe skips exactly what
        # the expansion passes through untouched; the substring test
        # comes first, the regex only when it hits (``thu``).
        has_hash = "h" in lowered and _ITEM_H.search(lowered) is not None
        display: Optional[list[str]] = (
            self._source.split() if has_hash else None
        )
        if len(fields) == 1 and fields[0] in _MACROS:
            self._source = fields[0]
            self._resolved = fields[0]
            fields = _MACROS[fields[0]].split()
            display = None  # macros carry no H item to resolve
        if not 5 <= len(fields) <= 7:
            raise ValueError(
                "expected 5 to 7 whitespace-separated cron fields "
                "(or a supported @-nickname), got {}".format(len(fields))
            )
        # kept for the dialect hint below: the columns as the user wrote
        # them, before the second/year columns are sliced away.
        raw_fields = tuple(fields)
        if display is not None:
            # Expand every H item BEFORE the ordinary field parse: the
            # substituted text is plain dialect, so matching and search
            # need no hash cases.  Runs over the original-case tokens so
            # ``resolved_source`` stays faithful to the user's spelling.
            try:
                expanded = [
                    _expand_hash_field(text, spec, hash_key)
                    for text, spec in zip(
                        display, _LAYOUTS[len(fields)], strict=True
                    )
                ]
            except ValueError as err:
                hint = _quartz_hint(raw_fields)
                if hint is not None:
                    raise ValueError("{} ({})".format(err, hint)) from None
                raise
            self._resolved = " ".join(expanded)
            fields = [text.lower() for text in expanded]
        # 5 fields: implicit second 0, any year.  6 fields: a trailing year
        # column.  7 fields: a leading second column as well.
        if len(fields) == 7:
            second_text = fields[0]
            fields = fields[1:]
        else:
            second_text = "0"
        if len(fields) == 6:
            year_text: Optional[str] = fields[5]
            if year_text == "*":
                year_text = None  # matches like an absent column
        else:
            year_text = None
        # Quartz compatibility: '?' alone in a day field reads as '*'.
        # ONLY the day fields: a '?' anywhere else keeps failing (with a
        # hint), which turns a mis-pasted seconds-first Quartz layout into
        # a clear error instead of a silently shifted schedule.
        dom_text = "*" if fields[2] == "?" else fields[2]
        dow_text = "*" if fields[4] == "?" else fields[4]
        try:
            self._seconds = _parse_plain(second_text, _SECOND)
            self._minutes = _parse_plain(fields[0], _MINUTE)
            self._hours = _parse_plain(fields[1], _HOUR)
            (
                self._dom,
                self._dom_last_offsets,
                self._dom_nearest,
                self._dom_last_weekday,
            ) = _parse_dom(dom_text)
            self._months = _parse_plain(fields[3], _MONTH)
            self._dow, self._dow_last, self._dow_nth = _parse_dow(dow_text)
            self._years: Optional[frozenset[int]] = (
                _parse_plain(year_text, _YEAR)
                if year_text is not None
                else None
            )
        except ValueError as err:
            hint = _quartz_hint(raw_fields)
            if hint is not None:
                raise ValueError("{} ({})".format(err, hint)) from None
            raise
        # Pooled on the field sets they come from, so two tabs with the same
        # hour column share one tuple instead of holding a private copy each.
        self._seconds_sorted = _sorted_tuple(self._seconds)
        self._minutes_sorted = _sorted_tuple(self._minutes)
        self._hours_sorted = _sorted_tuple(self._hours)
        self._months_sorted = _sorted_tuple(self._months)
        self._dom_sorted = _sorted_tuple(self._dom)
        # An empty tuple (not None) for an absent year column: the walks
        # already gate every use on ``self._years``, and the singleton keeps
        # the successor lookup's argument one plain type.
        self._years_sorted = (
            _sorted_tuple(self._years) if self._years is not None else ()
        )
        # _first_time/_last_time's answers for tod=None, built on first
        # use: eager tuples here cost ~140 bytes per parsed CronTab,
        # enough to trip mem.crontab_10k's gate.
        self._first_hms: Optional[_HMS] = None
        self._last_hms: Optional[_HMS] = None
        # Whether the day-of-week column constrains anything.  All seven
        # values makes the second half of the plain-day test a tautology,
        # letting _next_civil bisect straight through the day-of-month
        # list instead of stepping one calendar day at a time.
        self._dow_free = len(self._dow) == 7
        # Whether BOTH day columns are plain value sets (no L / W / #
        # member).  Then a day matches iff ``day in self._dom and dow in
        # self._dow``: an unrestricted column has already expanded to its
        # full range, so the both-restricted AND rule needs no special
        # case, and the civil walks test a day with two inline set lookups
        # instead of the _day_matches -> _dom_matches call pair.
        self._days_plain = not (
            self._dom_last_offsets
            or self._dom_nearest
            or self._dom_last_weekday
            or self._dow_last
            or self._dow_nth
        )
        # Fixed at parse time; every schedule payload asks (to decide
        # whether to emit a "resolved" field).
        self._resolved_differs = self._resolved != self._source

    # ------------------------------------------------------------------
    # Introspection
    # ------------------------------------------------------------------
    def __str__(self) -> str:
        return self._source

    def __repr__(self) -> str:
        return "CronTab({!r})".format(self._source)

    @property
    def resolved_source(self) -> str:
        """The source with every ``H`` item replaced by its hashed values.

        Equal to ``str(self)`` for an expression without ``H``.  Always
        plain dialect, so it re-parses without a hash key; the dashboards'
        client-side engines and the fire previews run on this text.
        """
        return self._resolved

    @property
    def resolved_differs(self) -> bool:
        """Whether :attr:`resolved_source` says more than ``str(self)``.

        True only for an expression that actually carried an ``H`` item;
        payload builders gate their "resolved" field on this flag.
        """
        return self._resolved_differs

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, CronTab):
            return False
        if self is other:
            return True
        # Equal resolved sources imply equal fields (all are parsed from
        # that text).  The converse does not hold (``*/5`` vs ``0-59/5``),
        # which is why a mismatch falls through to the full comparison
        # rather than returning False.
        if self._resolved == other._resolved:
            return True
        return (
            self._seconds == other._seconds
            and self._minutes == other._minutes
            and self._hours == other._hours
            and self._dom == other._dom
            and self._dom_last_offsets == other._dom_last_offsets
            and self._dom_nearest == other._dom_nearest
            and self._dom_last_weekday == other._dom_last_weekday
            and self._months == other._months
            and self._dow == other._dow
            and self._dow_last == other._dow_last
            and self._dow_nth == other._dow_nth
            and self._years == other._years
        )

    # __eq__ without __hash__ makes instances unhashable, matching the old
    # class; nothing in cronstable keys on a CronTab.

    # ------------------------------------------------------------------
    # Parsed field sets
    # ------------------------------------------------------------------
    # Ground truth for the tooling around the engine (linter, describers,
    # preview endpoint).  Every value is immutable and already normalized.

    @property
    def seconds(self) -> frozenset[int]:
        """Matching seconds, 0-59 (``{0}`` unless a 7-field form set them)."""
        return self._seconds

    @property
    def minutes(self) -> frozenset[int]:
        """Matching minutes, 0-59."""
        return self._minutes

    @property
    def hours(self) -> frozenset[int]:
        """Matching hours, 0-23."""
        return self._hours

    @property
    def days_of_month(self) -> frozenset[int]:
        """Explicit day-of-month values, 1-31 (a bare ``L`` is separate)."""
        return self._dom

    @property
    def last_day_of_month(self) -> bool:
        """Whether a bare ``L`` also matches each month's final day."""
        return 0 in self._dom_last_offsets

    @property
    def last_day_offsets(self) -> frozenset[int]:
        """Offsets back from the month's final day (``L`` = 0, ``L-3`` = 3)."""
        return self._dom_last_offsets

    @property
    def nearest_weekday_days(self) -> frozenset[int]:
        """Target days of ``<n>W`` items (fire on the weekday nearest each)."""
        return self._dom_nearest

    @property
    def last_weekday_of_month(self) -> bool:
        """Whether ``LW`` also matches each month's last weekday (Mon-Fri)."""
        return self._dom_last_weekday

    @property
    def months(self) -> frozenset[int]:
        """Matching months, 1-12."""
        return self._months

    @property
    def days_of_week(self) -> frozenset[int]:
        """Matching weekdays, 0-6 with Sunday as 0 (7 already folded)."""
        return self._dow

    @property
    def last_days_of_week(self) -> frozenset[int]:
        """Weekdays matched only as the month's LAST such day (``L<n>``)."""
        return self._dow_last

    @property
    def nth_days_of_week(self) -> frozenset[tuple[int, int]]:
        """(weekday, n) pairs from ``<d>#<n>``: the month's n-th such day."""
        return self._dow_nth

    @property
    def years(self) -> Optional[frozenset[int]]:
        """Explicit years, or ``None`` when the column is ``*`` or absent."""
        return self._years

    # ------------------------------------------------------------------
    # Matching
    # ------------------------------------------------------------------
    def test(self, entry: datetime.datetime) -> bool:
        """Whether ``entry``'s civil fields match (microseconds ignored)."""
        # a pure AND of set probes, so the order is free: the minute
        # column rejects most often (every scheduler probe carries second
        # 0, which nearly every schedule accepts), so it goes first
        if not (
            entry.minute in self._minutes
            and entry.hour in self._hours
            and entry.second in self._seconds
            and entry.month in self._months
            and (self._years is None or entry.year in self._years)
        ):
            return False
        if self._days_plain:
            # Plain day columns reduce the day test to set membership
            # (the _days_plain contract); the month length feeds only
            # the L / W / # rules, so it stays uncomputed here.
            if entry.day not in self._dom:
                return False
            return self._dow_free or (entry.weekday() + 1) % 7 in self._dow
        # month length computed only once the cheaper column checks pass
        month_end = _month_end(entry.year, entry.month)
        return self._day_matches(entry.year, entry.month, entry.day, month_end)

    def _day_matches(
        self, year: int, month: int, day: int, month_end: int
    ) -> bool:
        """The AND of the day-of-month and day-of-week constraints.

        Only :meth:`test` calls this; the civil walks inline the same
        dom/dow pair with the weekday carried forward day to day.
        """
        if not self._dom_matches(year, month, day, month_end):
            return False
        # Python weekday(): Mon=0..Sun=6 -> cron: Sun=0..Sat=6.
        dow = (datetime.date(year, month, day).weekday() + 1) % 7
        return self._dow_matches(dow, day, month_end)

    def _dow_matches(self, dow: int, day: int, month_end: int) -> bool:
        """The day-of-week side: plain values, the L family, the # family."""
        if dow in self._dow:
            return True
        if (
            dow in self._dow_last
            and day > month_end - 7  # the month's last such weekday
        ):
            return True
        if not self._dow_nth:
            return False
        # (day - 1) // 7 + 1 is which occurrence of its weekday this is
        return (dow, (day - 1) // 7 + 1) in self._dow_nth

    def _dom_matches(
        self, year: int, month: int, day: int, month_end: int
    ) -> bool:
        """The day-of-month side: plain values, the L family, the W family."""
        if day in self._dom:
            return True
        if (
            self._dom_last_offsets
            and (month_end - day) in self._dom_last_offsets
        ):
            return True
        # a W shift moves at most two days, so the range guards skip the
        # date construction on every day the item cannot land on
        if (
            self._dom_last_weekday
            and day >= month_end - 2  # LW lands on the final three days
            and day == _shift_to_weekday(year, month, month_end, month_end)
        ):
            return True
        if self._dom_nearest:
            for target in self._dom_nearest:
                if not target - 2 <= day <= target + 2 or target > month_end:
                    continue
                if day == _shift_to_weekday(year, month, target, month_end):
                    return True
        return False

    # ------------------------------------------------------------------
    # Next occurrence
    # ------------------------------------------------------------------
    @staticmethod
    def _gap_rewound_seed(
        now: datetime.datetime, now_utc: datetime.datetime
    ) -> datetime.datetime:
        """The naive civil seed for an aware forward scan from ``now``.

        Normally ``now``'s wall-clock label, but a spring-forward shortly
        before ``now`` moves every fire whose label sat inside the gap to
        a REAL instant up to a full shift LATER, so such a fire can still
        be in the FUTURE while its label is behind ``now``'s (a scan
        seeded at now's label would walk past it to tomorrow).  When the
        offset grew within :data:`_GAP_PROBE` AND shifted fires can still
        be pending, rewind the seed by the jump so the walk GENERATES
        those labels; the resolved-UTC guard in :meth:`next` /
        :meth:`occurrences` discards non-future candidates, so
        over-generation is never a wrong answer.  Callers skip this for a
        fixed-offset :class:`datetime.timezone`, whose immutable offset
        makes the probe provably a no-op.
        """
        civil = now.replace(tzinfo=None)
        try:
            earlier = (now_utc - _GAP_PROBE).astimezone(now.tzinfo)
        except (OverflowError, OSError):  # pragma: no cover - datetime.min
            return civil
        off_now = now.utcoffset()
        off_then = earlier.utcoffset()
        if off_now is None or off_then is None or off_now <= off_then:
            return civil  # no spring-forward inside the window
        jump = off_now - off_then
        # Only rewind while shifted fires can still be pending: gap labels
        # resolve to instants within [transition, transition + jump), so
        # once the offset ``jump`` seconds ago already equals ``now``'s,
        # the whole affected window is behind us.
        at_edge = (now_utc - jump).astimezone(now.tzinfo).utcoffset()
        if at_edge == off_now:
            return civil
        return civil - jump

    def next(
        self,
        now: Optional[datetime.datetime] = None,
        default_utc: bool = False,
    ) -> Optional[float]:
        """Seconds until the next occurrence STRICTLY after ``now``.

        ``None`` when the schedule never occurs again (the search stops at
        year 2099).  For an aware ``now`` the result is true elapsed
        seconds: the matching civil instant is resolved in ``now``'s zone
        (``fold=0``), so a DST change inside the interval is accounted
        for.  ``default_utc`` only matters when ``now`` is omitted: it
        picks the UTC wall clock instead of the local one.
        """
        if now is None:
            now = _default_now(default_utc)
        if now.tzinfo is None:
            # naive: already its own civil label
            target = self._next_civil(now)
            if target is None:
                return None
            return (target - now).total_seconds()
        if type(now.tzinfo) is datetime.timezone:
            # A fixed offset makes the whole UTC round trip below an
            # identity: the immutable offset cancels in the comparison AND
            # the subtraction, and _next_civil already answers strictly
            # after its seed, so the guard always passes and the retry
            # loop provably runs once.  UTC jobs arm through here; a
            # local-clock job arms against LOCAL_ZONE, whose offset moves,
            # and takes the aware path below.  ``type(...) is`` keeps the
            # precondition literal; CPython refuses to subclass
            # datetime.timezone anyway.
            civil = now.replace(tzinfo=None)
            target = self._next_civil(civil)
            if target is None:
                return None
            return (target - civil).total_seconds()
        # Aware: the delay to the next REAL instant, i.e. the first
        # :meth:`occurrences` yield after ``now``.  Each civil match is
        # resolved in the zone (fold=0) and compared through UTC, so a
        # gap-swallowed match counts once at its shifted label and a wall
        # time already passed on the first leg of a fall-back hour is not
        # offered again on the second.  The seed may sit BEFORE now's
        # label (see _gap_rewound_seed); the resolved-UTC guard below
        # keeps the earlier seed from ever RETURNING a past instant.
        now_utc = now.astimezone(_UTC)
        civil = self._gap_rewound_seed(now, now_utc)
        while True:
            target = self._next_civil(civil)
            if target is None:
                return None
            resolved_utc = target.replace(tzinfo=now.tzinfo).astimezone(_UTC)
            if resolved_utc > now_utc:
                return (resolved_utc - now_utc).total_seconds()
            resolved_civil = resolved_utc.astimezone(now.tzinfo).replace(
                tzinfo=None
            )
            civil = max(target, resolved_civil)

    def next_local(self, now_utc: datetime.datetime) -> Optional[float]:
        """Seconds until the next occurrence STRICTLY after the aware
        instant ``now_utc`` on the host clock: what :meth:`next` answers
        for ``now_utc.astimezone(LOCAL_ZONE)``, taken on the fixed-offset
        path whenever :meth:`LocalZone.fixed_frame` vouches for the
        answer.
        """
        fixed, good_to = LOCAL_ZONE.fixed_frame(now_utc)
        if fixed is not None:
            delay = self.next(now=now_utc.astimezone(fixed))
            if delay is None:
                # no civil match before the horizon: the same walk from
                # the same label, whichever frame reads it
                return None
            # ``now_utc + timedelta(seconds=delay) <= good_to`` without
            # building either object: ``delay`` is a whole number of
            # microseconds and total_seconds() rounds monotonically, so
            # the float comparison is exact over the engine's range
            if delay <= (good_to - now_utc).total_seconds():
                return delay
        return self.next(now=now_utc.astimezone(LOCAL_ZONE))

    def _next_civil(
        self, civil: datetime.datetime
    ) -> Optional[datetime.datetime]:
        """Smallest whole-second civil instant strictly after ``civil``."""
        # a whole-second seed (every occurrences() cursor) skips the copy
        base = (
            civil.replace(microsecond=0) if civil.microsecond else civil
        ) + _ONE_SECOND
        year, month, day = base.year, base.month, base.day
        # the seed itself is the time-of-day floor: the time walks read
        # only hour/minute/second, so no datetime.time is sliced off it
        tod: Optional[_TimeOfDay] = base
        years = self._years
        years_sorted = self._years_sorted
        months = self._months
        months_sorted = self._months_sorted
        days_plain = self._days_plain
        horizon = _YEAR_HORIZON
        while year <= horizon:
            # membership against the frozenset, not a scan of the tuple
            if years is not None and year not in years:
                next_year = self._next_in(years_sorted, year)
                if next_year is None:
                    return None
                year, month, day, tod = next_year, 1, 1, None
                continue
            if month not in months:
                nxt = self._next_in(months_sorted, month)
                if nxt is None:
                    year, month = year + 1, months_sorted[0]
                else:
                    month = nxt
                day, tod = 1, None
                continue
            month_end = _month_end(year, month)
            # ``day`` is always a real day of this month here (base's own
            # day on the first pass, 1 after), so the weekday seeds below
            # cannot be asked for a date that does not exist.
            if days_plain:
                found = self._next_plain_day(year, month, day, month_end, tod)
                if found is not None:
                    return found
            else:
                # bound here, not once per call: the plain-day path (most
                # schedules) never reads them
                dom_matches = self._dom_matches
                dow_matches = self._dow_matches
                at_first_time = self._at_first_time
                # Python weekday(): Mon=0..Sun=6 -> cron: Sun=0..Sat=6.
                dow = (datetime.date(year, month, day).weekday() + 1) % 7
                while day <= month_end:
                    if dom_matches(
                        year, month, day, month_end
                    ) and dow_matches(dow, day, month_end):
                        found = at_first_time(year, month, day, tod)
                        if found is not None:
                            return found
                    day += 1
                    dow = dow + 1 if dow < 6 else 0
                    tod = None
            month += 1
            day, tod = 1, None
            if month > 12:
                year, month = year + 1, 1
        return None

    def _next_plain_day(
        self,
        year: int,
        month: int,
        day: int,
        month_end: int,
        tod: Optional[_TimeOfDay],
    ) -> Optional[datetime.datetime]:
        """Forward day scan for a tab whose day columns are plain sets.

        ``None`` when this month holds no matching day at or after ``day``
        (with a matching time of day), so the caller moves to the next
        month.  ``tod`` is the time-of-day floor and applies to ``day``
        ALONE: every later day of the month starts from midnight, so it is
        dropped the moment the scan steps off the seed.
        """
        if self._dow_free:
            # Day-of-week unrestricted, so only the day-of-month list
            # constrains the day: bisect to the first listed day at or
            # after ``day``; the calendar days in between are never
            # tested.  Two candidates at most: the seed day (the only
            # one the floor applies to) and, once its times are spent,
            # the next listed day, which starts from midnight.
            dom_sorted = self._dom_sorted
            index = bisect_left(dom_sorted, day)
            if index == len(dom_sorted):
                return None
            first = dom_sorted[index]
            if first > month_end:
                return None
            if first == day:
                found = self._at_first_time(year, month, day, tod)
                if found is not None:
                    return found
                index += 1
                if index == len(dom_sorted):
                    return None
                first = dom_sorted[index]
                if first > month_end:
                    return None
            # from midnight every column's first value matches: never None
            hms = self._first_time(None)
            assert hms is not None
            return datetime.datetime(
                year, month, first, hms[0], hms[1], hms[2]
            )
        # Two set lookups per candidate day, the weekday carried forward
        # day to day.  Exactly the dom/dow test of _next_civil's L/W/#
        # branch with the plain sets (see _days_plain).
        dom = self._dom
        dow_set = self._dow
        # Python weekday(): Mon=0..Sun=6 -> cron: Sun=0..Sat=6.
        dow = (datetime.date(year, month, day).weekday() + 1) % 7
        while day <= month_end:
            if day in dom and dow in dow_set:
                found = self._at_first_time(year, month, day, tod)
                if found is not None:
                    return found
            day += 1
            dow = dow + 1 if dow < 6 else 0
            tod = None
        return None

    def _at_first_time(
        self,
        year: int,
        month: int,
        day: int,
        tod: Optional[_TimeOfDay],
    ) -> Optional[datetime.datetime]:
        """``(year, month, day)`` at its earliest matching time, if any.

        ``None`` when no matching time of day sits at or after ``tod``
        (the matched day is spent).  Shared by :meth:`_next_civil`'s two
        day loops so the plain-day fast path and the L/W/# path cannot
        drift apart.
        """
        hms = self._first_time(tod)
        if hms is None:
            return None
        return datetime.datetime(year, month, day, hms[0], hms[1], hms[2])

    def _at_last_time(
        self,
        year: int,
        month: int,
        day: int,
        tod: Optional[_TimeOfDay],
    ) -> Optional[datetime.datetime]:
        """The backward mirror of :meth:`_at_first_time`, for
        :meth:`_prev_civil`."""
        hms = self._last_time(tod)
        if hms is None:
            return None
        return datetime.datetime(year, month, day, hms[0], hms[1], hms[2])

    @staticmethod
    def _next_in(ordered: tuple[int, ...], current: int) -> Optional[int]:
        """First element of ``ordered`` greater than ``current``."""
        index = bisect_right(ordered, current)
        return ordered[index] if index < len(ordered) else None

    def _first_time(self, at_or_after: Optional[_TimeOfDay]) -> Optional[_HMS]:
        """Earliest matching time of day, at/after ``at_or_after`` if set.

        Each column is bisected, not scanned.  The fall-throughs preserve
        the exact order of preference: a spent seconds column moves to the
        next minute of the SAME hour, and only a spent minutes column
        moves to the next hour.  Returns a plain ``(hour, minute, second)``
        because the only consumer feeds a datetime constructor.
        """
        if at_or_after is None:
            hms = self._first_hms
            if hms is None:
                hms = self._first_hms = (
                    self._hours_sorted[0],
                    self._minutes_sorted[0],
                    self._seconds_sorted[0],
                )
            return hms
        hours = self._hours_sorted
        minutes = self._minutes_sorted
        seconds = self._seconds_sorted
        hour = at_or_after.hour
        index = bisect_left(hours, hour)
        if index == len(hours):
            return None
        if hours[index] > hour:
            return (hours[index], minutes[0], seconds[0])
        minute = at_or_after.minute
        m_index = bisect_left(minutes, minute)
        if m_index < len(minutes):
            if minutes[m_index] > minute:
                return (hour, minutes[m_index], seconds[0])
            s_index = bisect_left(seconds, at_or_after.second)
            if s_index < len(seconds):
                return (hour, minute, seconds[s_index])
            if m_index + 1 < len(minutes):
                return (hour, minutes[m_index + 1], seconds[0])
        if index + 1 < len(hours):
            return (hours[index + 1], minutes[0], seconds[0])
        return None

    # ------------------------------------------------------------------
    # Previous occurrence
    # ------------------------------------------------------------------
    def prev(
        self,
        now: Optional[datetime.datetime] = None,
        default_utc: bool = False,
    ) -> Optional[float]:
        """Seconds since the most recent occurrence STRICTLY before ``now``.

        The mirror of :meth:`next`: ``None`` when the schedule has no
        occurrence at or after 1970 (the year column's floor).  For an
        aware ``now`` the result is true elapsed seconds since the most
        recent REAL instant, under the same DST policy as
        :meth:`occurrences`.  Callers use this for missed-run and late-run
        detection.
        """
        if now is None:
            now = _default_now(default_utc)
        if now.tzinfo is None:
            # already naive: see the matching note in next()
            target = self._prev_civil(now)
            if target is None:
                return None
            return (now - target).total_seconds()
        # Aware: a backward civil scan alone goes wrong at DST edges (a
        # gap match resolves FORWARD, possibly past ``now``; on the second
        # leg of a fall-back hour the most recent fire lives at a LATER
        # civil label than ``now``'s).  So walk back to a match whose
        # label the zone leaves in place, then replay the forward iterator
        # (the fire policy itself) and keep the last instant before now.
        tz = now.tzinfo
        utc = _UTC
        now_utc = now.astimezone(utc)
        # No occurrence lives past _YEAR_HORIZON, so clamp a far-future
        # ``now`` (a schema-valid MCP/web ``at`` argument) to the horizon's
        # edge.  Without the clamp every anchor past the horizon replays an
        # EMPTY forward iterator and the loop steps back one fire instant
        # per pass: hours of event-loop starvation for a dense schedule.
        civil = min(now.replace(tzinfo=None), _HORIZON_EDGE)
        anchor = self._prev_civil(civil)
        while anchor is not None:
            resolved = anchor.replace(tzinfo=tz).astimezone(utc).astimezone(tz)
            if resolved.replace(tzinfo=None) == anchor:
                last: Optional[datetime.datetime] = None
                start = (anchor - _ONE_SECOND).replace(tzinfo=tz)
                for instant in self.occurrences(start):
                    instant_utc = instant.astimezone(utc)
                    if instant_utc >= now_utc:
                        break
                    last = instant_utc
                if last is not None:
                    return (now_utc - last).total_seconds()
            anchor = self._prev_civil(anchor)
        return None

    def _prev_civil(
        self, civil: datetime.datetime
    ) -> Optional[datetime.datetime]:
        """Largest whole-second civil instant strictly before ``civil``."""
        if civil.microsecond:
            base = civil.replace(microsecond=0)
        else:
            base = civil - _ONE_SECOND
        year, month, day = base.year, base.month, base.day
        tod: Optional[_TimeOfDay] = base  # the ceiling; see _next_civil
        years = self._years
        years_sorted = self._years_sorted
        months = self._months
        months_sorted = self._months_sorted
        days_plain = self._days_plain
        floor = _YEAR_FLOOR
        while year >= floor:
            if years is not None and year not in years:
                prev_year = self._prev_in(years_sorted, year)
                if prev_year is None:
                    return None
                year, month, day, tod = prev_year, 12, 31, None
                continue
            if month not in months:
                prv = self._prev_in(months_sorted, month)
                if prv is None:
                    year, month = year - 1, months_sorted[-1]
                else:
                    month = prv
                day, tod = 31, None
                continue
            month_end = _month_end(year, month)
            if day > month_end:
                day = month_end  # clamp the rollback sentinel into the month
            # the clamp above leaves ``day`` a real day of this month, so the
            # weekday seeds below cannot be asked for a date that does not
            # exist.
            if days_plain:
                found = self._prev_plain_day(year, month, day, tod)
                if found is not None:
                    return found
            else:
                # bound on the L/W/# path alone, as in _next_civil
                dom_matches = self._dom_matches
                dow_matches = self._dow_matches
                at_last_time = self._at_last_time
                # Python weekday(): Mon=0..Sun=6 -> cron: Sun=0..Sat=6.
                dow = (datetime.date(year, month, day).weekday() + 1) % 7
                while day >= 1:
                    if dom_matches(
                        year, month, day, month_end
                    ) and dow_matches(dow, day, month_end):
                        found = at_last_time(year, month, day, tod)
                        if found is not None:
                            return found
                    day -= 1
                    dow = dow - 1 if dow > 0 else 6
                    tod = None
            month -= 1
            day, tod = 31, None
            if month < 1:
                year, month = year - 1, 12
        return None

    def _prev_plain_day(
        self,
        year: int,
        month: int,
        day: int,
        tod: Optional[_TimeOfDay],
    ) -> Optional[datetime.datetime]:
        """The backward mirror of :meth:`_next_plain_day`.

        ``day`` is already clamped into the month by the caller, so no
        ``month_end`` is owed here.
        """
        if self._dow_free:
            # the mirror of _next_plain_day's two candidates: the seed
            # day under the ceiling, then the previous listed day from
            # the end of the day
            dom_sorted = self._dom_sorted
            index = bisect_right(dom_sorted, day) - 1
            if index < 0:
                return None
            last = dom_sorted[index]
            if last == day:
                found = self._at_last_time(year, month, day, tod)
                if found is not None:
                    return found
                index -= 1
                if index < 0:
                    return None
                last = dom_sorted[index]
            # from the end of the day every column's last value matches
            hms = self._last_time(None)
            assert hms is not None
            return datetime.datetime(year, month, last, hms[0], hms[1], hms[2])
        dom = self._dom
        dow_set = self._dow
        dow = (datetime.date(year, month, day).weekday() + 1) % 7
        while day >= 1:
            if day in dom and dow in dow_set:
                found = self._at_last_time(year, month, day, tod)
                if found is not None:
                    return found
            day -= 1
            dow = dow - 1 if dow > 0 else 6
            tod = None
        return None

    @staticmethod
    def _prev_in(ordered: tuple[int, ...], current: int) -> Optional[int]:
        """Last element of ``ordered`` less than ``current``."""
        index = bisect_left(ordered, current) - 1
        return ordered[index] if index >= 0 else None

    def _last_time(self, at_or_before: Optional[_TimeOfDay]) -> Optional[_HMS]:
        """Latest matching time of day, at/before ``at_or_before`` if set.

        The backward mirror of :meth:`_first_time`, with the order of
        preference reversed and the same ``(hour, minute, second)`` return.
        """
        if at_or_before is None:
            hms = self._last_hms
            if hms is None:
                hms = self._last_hms = (
                    self._hours_sorted[-1],
                    self._minutes_sorted[-1],
                    self._seconds_sorted[-1],
                )
            return hms
        hours = self._hours_sorted
        minutes = self._minutes_sorted
        seconds = self._seconds_sorted
        hour = at_or_before.hour
        index = bisect_right(hours, hour) - 1
        if index < 0:
            return None
        if hours[index] < hour:
            return (hours[index], minutes[-1], seconds[-1])
        minute = at_or_before.minute
        m_index = bisect_right(minutes, minute) - 1
        if m_index >= 0:
            if minutes[m_index] < minute:
                return (hour, minutes[m_index], seconds[-1])
            s_index = bisect_right(seconds, at_or_before.second) - 1
            if s_index >= 0:
                return (hour, minute, seconds[s_index])
            if m_index >= 1:
                return (hour, minutes[m_index - 1], seconds[-1])
        if index >= 1:
            return (hours[index - 1], minutes[-1], seconds[-1])
        return None

    # ------------------------------------------------------------------
    # Occurrence iteration
    # ------------------------------------------------------------------
    def occurrences(
        self,
        start: Optional[datetime.datetime] = None,
        default_utc: bool = False,
    ) -> Iterator[datetime.datetime]:
        """Yield successive fire instants strictly after ``start``.

        Exactly the instants the scheduler would fire, in order, ending at
        the 2099 horizon.  With an aware ``start`` every yield is an aware
        datetime in its zone and the iteration steps through REAL
        instants: a spring-forward-skipped wall time is yielded once at
        its shifted label, a repeated fall-back wall time on its first
        occurrence only, so one real instant is never yielded twice.  With
        a naive ``start`` the yields are civil wall-clock datetimes.
        ``default_utc`` matters only when ``start`` is omitted, as in
        :meth:`next`.
        """
        if start is None:
            start = _default_now(default_utc)
        tz = start.tzinfo
        # a naive start already IS its own civil label
        civil = start
        if type(tz) is datetime.timezone:
            # Fixed offset, the same theorem next() exploits: the offset
            # cancels, so every candidate resolves to its own label and
            # none can land at or before ``start``.  No gap to rewind
            # over, no fold to honour, no instant to re-render.
            civil = start.replace(tzinfo=None)
            while True:
                target = self._next_civil(civil)
                if target is None:
                    return
                yield target.replace(tzinfo=tz)
                civil = target
        if tz is not None:
            # Mirror next()'s aware framing exactly, so the first yield IS
            # start + next(now=start): ``start_utc`` honours start.fold (a
            # fold=1 start must not replay the first leg's already-past
            # fires), and the seed may be rewound below start's label
            # right after a spring-forward (see _gap_rewound_seed).  The
            # guard in the loop then admits exactly the candidates whose
            # resolved instant is strictly after start.
            start_utc = start.astimezone(_UTC)
            civil = self._gap_rewound_seed(start, start_utc)
        while True:
            target = self._next_civil(civil)
            if target is None:
                return
            if tz is None:
                yield target
                civil = target
                continue
            # Resolve in the zone (fold=0, next()'s rule), then re-render
            # through UTC: a nonexistent spring-forward wall time comes back
            # as the label the wall clock actually shows at that instant,
            # and continuing the civil search from the rendered label steps
            # past both the skipped hour and a fall-back repeat.
            resolved_utc = target.replace(tzinfo=tz).astimezone(_UTC)
            resolved = resolved_utc.astimezone(tz)
            if resolved_utc <= start_utc:
                # already past in REAL time (a fold=1 start, or a rewound
                # seed's pre-start candidates): advance the civil cursor
                # without yielding, exactly as next() steps past them.
                civil = max(target, resolved.replace(tzinfo=None))
                continue
            yield resolved
            civil = resolved.replace(tzinfo=None)
