#!/usr/bin/env bash
#
# Install the public demo daemon and its Cloudflare Tunnel as launchd agents,
# for a macOS host with no container runtime. The container path
# (../docker-compose.yml) is the default; see ../README.md for when to prefer
# which. Safe to re-run: it re-derives the config and reloads both agents.
#
#   brew install cronstable cloudflared
#   cloudflared tunnel login
#   cloudflared tunnel create cronstable-demo
#   cloudflared tunnel route dns cronstable-demo demo.cronstable.com
#   ./install.sh [tunnel-name]            # default: cronstable-demo
#
# The view token is public by design; override to rotate:
#   CRONSTABLE_DEMO_VIEW_TOKEN=new-value ./install.sh
#
set -euo pipefail

TUNNEL_NAME="${1:-cronstable-demo}"
VIEW_TOKEN="${CRONSTABLE_DEMO_VIEW_TOKEN:-cronstable-public-demo-view}"
HOSTNAME_PUBLIC="${CRONSTABLE_DEMO_HOSTNAME:-demo.cronstable.com}"

die() { printf 'install.sh: %s\n' "$1" >&2; exit 1; }

[ "$(uname -s)" = "Darwin" ] || die "launchd agents are macOS only"
command -v brew        >/dev/null || die "Homebrew not found"
command -v cronstable  >/dev/null || die "cronstable not on PATH (brew install cronstable)"
command -v cloudflared >/dev/null || die "cloudflared not on PATH (brew install cloudflared)"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_CONFIG="$HERE/../cronstable.yaml"
[ -f "$SRC_CONFIG" ] || die "cannot find $SRC_CONFIG"

PREFIX="$(brew --prefix)"
ETC_DIR="$PREFIX/etc/cronstable-demo"
STATE_DIR="$PREFIX/var/cronstable-demo/state"
LOG_DIR="$PREFIX/var/log"
AGENT_DIR="$HOME/Library/LaunchAgents"
CF_DIR="$HOME/.cloudflared"

# Resolve the tunnel by name. `tunnel create` must have run already; doing it
# here would make re-running the script mint duplicate tunnels.
TUNNEL_ID="$(cloudflared tunnel list --output json 2>/dev/null | python3 -c "
import json, sys
name = sys.argv[1]
try:
    tunnels = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for t in tunnels:
    # A live tunnel carries Go's zero timestamp here, not an empty string.
    stamp = t.get('deleted_at') or ''
    deleted = bool(stamp) and not stamp.startswith('0001-01-01')
    if t.get('name') == name and not deleted:
        print(t['id']); break
" "$TUNNEL_NAME")"
[ -n "$TUNNEL_ID" ] || die "no tunnel named '$TUNNEL_NAME' (run: cloudflared tunnel create $TUNNEL_NAME)"

CREDS="$CF_DIR/$TUNNEL_ID.json"
[ -f "$CREDS" ] || die "missing tunnel credentials $CREDS"

mkdir -p "$ETC_DIR" "$STATE_DIR" "$LOG_DIR" "$AGENT_DIR"

# The kit's config is written for a container. Retarget exactly two values for
# a non-container host, and fail loudly if either stops matching upstream
# rather than silently deploying a config that differs from what is reviewed.
#
#   state.path  -> a writable prefix path, since /var/lib needs root
#   listen      -> loopback, because the container published only a loopback
#                  port; binding the wildcard natively would newly expose the
#                  daemon to the LAN
grep -q '^  path: /var/lib/cronstable/state$'  "$SRC_CONFIG" || die "state.path line not found in cronstable.yaml; update install.sh"
grep -q '^    - http://0.0.0.0:8080$'          "$SRC_CONFIG" || die "listen line not found in cronstable.yaml; update install.sh"

sed -e "s#^  path: /var/lib/cronstable/state\$#  path: $STATE_DIR#" \
    -e "s#^    - http://0.0.0.0:8080\$#    - http://127.0.0.1:8080#" \
    "$SRC_CONFIG" > "$ETC_DIR/cronstable.yaml"

CRONSTABLE_DEMO_VIEW_TOKEN="$VIEW_TOKEN" \
  cronstable -c "$ETC_DIR/cronstable.yaml" --validate-config >/dev/null \
  || die "derived config failed validation"

cat > "$CF_DIR/config.yml" <<EOF
# Generated by example/demo-instance/launchd/install.sh
#
# Native counterpart of the \`tunnel\` service in ../docker-compose.yml. There
# the tunnel reached the daemon over the compose network; here both processes
# are launchd agents on one host, so it is plain loopback.
tunnel: $TUNNEL_ID
credentials-file: $CREDS

# Ride out a daemon restart instead of surfacing 502s to the demo.
retries: 5
grace-period: 30s

ingress:
  - hostname: $HOSTNAME_PUBLIC
    service: http://127.0.0.1:8080
  - service: http_status:404
EOF

# Note for editors: a literal double hyphen is illegal inside an XML comment,
# and plutil accepts it anyway. Keep prose in these comments free of it.
cat > "$AGENT_DIR/com.cronstable.demo.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by example/demo-instance/launchd/install.sh. Edits are lost on re-run. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.cronstable.demo</string>
    <key>ProgramArguments</key>
    <array>
        <string>$PREFIX/bin/cronstable</string>
        <string>-c</string>
        <string>$ETC_DIR/cronstable.yaml</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <!-- Public by design; it ships in the companion app. -->
        <key>CRONSTABLE_DEMO_VIEW_TOKEN</key>
        <string>$VIEW_TOKEN</string>
        <!-- launchd hands out a minimal PATH, and the nightly-archive DAG
             shells out to the cronstable CLI for xcom. -->
        <key>PATH</key>
        <string>$PREFIX/bin:$PREFIX/sbin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    <key>WorkingDirectory</key>
    <string>$PREFIX/var/cronstable-demo</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <!-- Do not let a config error hot loop the machine. -->
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/cronstable-demo.out.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/cronstable-demo.err.log</string>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
EOF

cat > "$AGENT_DIR/com.cronstable.tunnel.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by example/demo-instance/launchd/install.sh. Edits are lost on re-run. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.cronstable.tunnel</string>
    <key>ProgramArguments</key>
    <array>
        <string>$PREFIX/bin/cloudflared</string>
        <string>--config</string>
        <string>$CF_DIR/config.yml</string>
        <string>--no-autoupdate</string>
        <string>tunnel</string>
        <string>run</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>10</integer>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/cronstable-tunnel.out.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/cronstable-tunnel.err.log</string>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
EOF

for label in com.cronstable.demo com.cronstable.tunnel; do
    plutil -lint "$AGENT_DIR/$label.plist" >/dev/null || die "$label.plist failed lint"
    # plutil tolerates malformed XML that a strict parser rejects, and these
    # files are re-read on every reboot. Check them the strict way too.
    python3 -c "import xml.dom.minidom,sys; xml.dom.minidom.parse(sys.argv[1])" \
        "$AGENT_DIR/$label.plist" || die "$label.plist is not well-formed XML"

    # bootout is asynchronous. Bootstrapping while the previous job is still
    # tearing down fails with EIO, and under `set -e` that would abort here,
    # after the bootout, leaving the service down and the demo dark. Wait for
    # the label to disappear, then retry the bootstrap rather than trusting it.
    launchctl bootout "gui/$UID/$label" 2>/dev/null || true
    for _ in $(seq 1 50); do
        launchctl print "gui/$UID/$label" >/dev/null 2>&1 || break
        sleep 0.2
    done

    booted=""
    for _ in 1 2 3 4 5; do
        if launchctl bootstrap "gui/$UID" "$AGENT_DIR/$label.plist" 2>/dev/null; then
            booted=yes
            break
        fi
        sleep 1
    done
    [ -n "$booted" ] || die "could not bootstrap $label; it is NOT running"
done

# Never report success for a daemon that did not actually come up.
code=""
for _ in $(seq 1 30); do
    code="$(curl -fsS -o /dev/null -w '%{http_code}' -m 5 \
        -H "Authorization: Bearer $VIEW_TOKEN" \
        http://127.0.0.1:8080/summary 2>/dev/null || true)"
    [ "$code" = "200" ] && break
    sleep 1
done
[ "$code" = "200" ] || die "daemon is not answering on 127.0.0.1:8080 (see $LOG_DIR/cronstable-demo.err.log)"

printf '\ninstalled:\n'
printf '  config   %s\n' "$ETC_DIR/cronstable.yaml"
printf '  state    %s\n' "$STATE_DIR"
printf '  logs     %s/cronstable-{demo,tunnel}.*.log\n' "$LOG_DIR"
printf '  tunnel   %s (%s)\n' "$TUNNEL_NAME" "$TUNNEL_ID"
printf '\nverify:\n'
printf '  curl -H "Authorization: Bearer %s" https://%s/summary\n\n' "$VIEW_TOKEN" "$HOSTNAME_PUBLIC"
